/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * GetGameSteamSummary200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-18T19:07:22.504751100+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class GetGameSteamSummary200Response {
  public static final String SERIALIZED_NAME_AVATAR = "avatar";
  @SerializedName(SERIALIZED_NAME_AVATAR)
  @javax.annotation.Nullable
  private String avatar;

  public static final String SERIALIZED_NAME_AVATARFULL = "avatarfull";
  @SerializedName(SERIALIZED_NAME_AVATARFULL)
  @javax.annotation.Nullable
  private String avatarfull;

  public static final String SERIALIZED_NAME_AVATARMEDIUM = "avatarmedium";
  @SerializedName(SERIALIZED_NAME_AVATARMEDIUM)
  @javax.annotation.Nullable
  private String avatarmedium;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @javax.annotation.Nullable
  private Integer code;

  public static final String SERIALIZED_NAME_COMMUNITYVISIBILITYSTATE = "communityvisibilitystate";
  @SerializedName(SERIALIZED_NAME_COMMUNITYVISIBILITYSTATE)
  @javax.annotation.Nullable
  private Integer communityvisibilitystate;

  public static final String SERIALIZED_NAME_LOCCOUNTRYCODE = "loccountrycode";
  @SerializedName(SERIALIZED_NAME_LOCCOUNTRYCODE)
  @javax.annotation.Nullable
  private String loccountrycode;

  public static final String SERIALIZED_NAME_PERSONANAME = "personaname";
  @SerializedName(SERIALIZED_NAME_PERSONANAME)
  @javax.annotation.Nullable
  private String personaname;

  public static final String SERIALIZED_NAME_PERSONASTATE = "personastate";
  @SerializedName(SERIALIZED_NAME_PERSONASTATE)
  @javax.annotation.Nullable
  private Integer personastate;

  public static final String SERIALIZED_NAME_PRIMARYCLANID = "primaryclanid";
  @SerializedName(SERIALIZED_NAME_PRIMARYCLANID)
  @javax.annotation.Nullable
  private String primaryclanid;

  public static final String SERIALIZED_NAME_PROFILESTATE = "profilestate";
  @SerializedName(SERIALIZED_NAME_PROFILESTATE)
  @javax.annotation.Nullable
  private Integer profilestate;

  public static final String SERIALIZED_NAME_PROFILEURL = "profileurl";
  @SerializedName(SERIALIZED_NAME_PROFILEURL)
  @javax.annotation.Nullable
  private String profileurl;

  public static final String SERIALIZED_NAME_REALNAME = "realname";
  @SerializedName(SERIALIZED_NAME_REALNAME)
  @javax.annotation.Nullable
  private String realname;

  public static final String SERIALIZED_NAME_STEAMID = "steamid";
  @SerializedName(SERIALIZED_NAME_STEAMID)
  @javax.annotation.Nullable
  private String steamid;

  public static final String SERIALIZED_NAME_TIMECREATED = "timecreated";
  @SerializedName(SERIALIZED_NAME_TIMECREATED)
  @javax.annotation.Nullable
  private Integer timecreated;

  public static final String SERIALIZED_NAME_TIMECREATED_STR = "timecreated_str";
  @SerializedName(SERIALIZED_NAME_TIMECREATED_STR)
  @javax.annotation.Nullable
  private String timecreatedStr;

  public GetGameSteamSummary200Response() {
  }

  public GetGameSteamSummary200Response avatar(@javax.annotation.Nullable String avatar) {
    this.avatar = avatar;
    return this;
  }

  /**
   * 32x32 像素的小尺寸头像URL。
   * @return avatar
   */
  @javax.annotation.Nullable
  public String getAvatar() {
    return avatar;
  }

  public void setAvatar(@javax.annotation.Nullable String avatar) {
    this.avatar = avatar;
  }


  public GetGameSteamSummary200Response avatarfull(@javax.annotation.Nullable String avatarfull) {
    this.avatarfull = avatarfull;
    return this;
  }

  /**
   * 184x184 像素的大尺寸头像URL。
   * @return avatarfull
   */
  @javax.annotation.Nullable
  public String getAvatarfull() {
    return avatarfull;
  }

  public void setAvatarfull(@javax.annotation.Nullable String avatarfull) {
    this.avatarfull = avatarfull;
  }


  public GetGameSteamSummary200Response avatarmedium(@javax.annotation.Nullable String avatarmedium) {
    this.avatarmedium = avatarmedium;
    return this;
  }

  /**
   * 64x64 像素的中等尺寸头像URL。
   * @return avatarmedium
   */
  @javax.annotation.Nullable
  public String getAvatarmedium() {
    return avatarmedium;
  }

  public void setAvatarmedium(@javax.annotation.Nullable String avatarmedium) {
    this.avatarmedium = avatarmedium;
  }


  public GetGameSteamSummary200Response code(@javax.annotation.Nullable Integer code) {
    this.code = code;
    return this;
  }

  /**
   * 状态码，200代表成功。
   * @return code
   */
  @javax.annotation.Nullable
  public Integer getCode() {
    return code;
  }

  public void setCode(@javax.annotation.Nullable Integer code) {
    this.code = code;
  }


  public GetGameSteamSummary200Response communityvisibilitystate(@javax.annotation.Nullable Integer communityvisibilitystate) {
    this.communityvisibilitystate = communityvisibilitystate;
    return this;
  }

  /**
   * 社区资料的可见性状态: 1&#x3D;私密, 3&#x3D;公开。
   * @return communityvisibilitystate
   */
  @javax.annotation.Nullable
  public Integer getCommunityvisibilitystate() {
    return communityvisibilitystate;
  }

  public void setCommunityvisibilitystate(@javax.annotation.Nullable Integer communityvisibilitystate) {
    this.communityvisibilitystate = communityvisibilitystate;
  }


  public GetGameSteamSummary200Response loccountrycode(@javax.annotation.Nullable String loccountrycode) {
    this.loccountrycode = loccountrycode;
    return this;
  }

  /**
   * 用户个人资料中设置的国家代码 (ISO 3166-1)，前提是用户已设置并公开。
   * @return loccountrycode
   */
  @javax.annotation.Nullable
  public String getLoccountrycode() {
    return loccountrycode;
  }

  public void setLoccountrycode(@javax.annotation.Nullable String loccountrycode) {
    this.loccountrycode = loccountrycode;
  }


  public GetGameSteamSummary200Response personaname(@javax.annotation.Nullable String personaname) {
    this.personaname = personaname;
    return this;
  }

  /**
   * 玩家的当前昵称。
   * @return personaname
   */
  @javax.annotation.Nullable
  public String getPersonaname() {
    return personaname;
  }

  public void setPersonaname(@javax.annotation.Nullable String personaname) {
    this.personaname = personaname;
  }


  public GetGameSteamSummary200Response personastate(@javax.annotation.Nullable Integer personastate) {
    this.personastate = personastate;
    return this;
  }

  /**
   * 用户当前的在线状态: 0-离线, 1-在线, 2-忙碌, 3-离开, 4-打盹, 5-想交易, 6-想玩。
   * @return personastate
   */
  @javax.annotation.Nullable
  public Integer getPersonastate() {
    return personastate;
  }

  public void setPersonastate(@javax.annotation.Nullable Integer personastate) {
    this.personastate = personastate;
  }


  public GetGameSteamSummary200Response primaryclanid(@javax.annotation.Nullable String primaryclanid) {
    this.primaryclanid = primaryclanid;
    return this;
  }

  /**
   * 玩家设置的主要部落的64位ID。
   * @return primaryclanid
   */
  @javax.annotation.Nullable
  public String getPrimaryclanid() {
    return primaryclanid;
  }

  public void setPrimaryclanid(@javax.annotation.Nullable String primaryclanid) {
    this.primaryclanid = primaryclanid;
  }


  public GetGameSteamSummary200Response profilestate(@javax.annotation.Nullable Integer profilestate) {
    this.profilestate = profilestate;
    return this;
  }

  /**
   * 如果用户设置了个人资料，则为1。
   * @return profilestate
   */
  @javax.annotation.Nullable
  public Integer getProfilestate() {
    return profilestate;
  }

  public void setProfilestate(@javax.annotation.Nullable Integer profilestate) {
    this.profilestate = profilestate;
  }


  public GetGameSteamSummary200Response profileurl(@javax.annotation.Nullable String profileurl) {
    this.profileurl = profileurl;
    return this;
  }

  /**
   * 用户的Steam社区个人资料页完整URL。
   * @return profileurl
   */
  @javax.annotation.Nullable
  public String getProfileurl() {
    return profileurl;
  }

  public void setProfileurl(@javax.annotation.Nullable String profileurl) {
    this.profileurl = profileurl;
  }


  public GetGameSteamSummary200Response realname(@javax.annotation.Nullable String realname) {
    this.realname = realname;
    return this;
  }

  /**
   * 用户的真实姓名，前提是用户已设置并公开。
   * @return realname
   */
  @javax.annotation.Nullable
  public String getRealname() {
    return realname;
  }

  public void setRealname(@javax.annotation.Nullable String realname) {
    this.realname = realname;
  }


  public GetGameSteamSummary200Response steamid(@javax.annotation.Nullable String steamid) {
    this.steamid = steamid;
    return this;
  }

  /**
   * 被查询用户的64位SteamID。
   * @return steamid
   */
  @javax.annotation.Nullable
  public String getSteamid() {
    return steamid;
  }

  public void setSteamid(@javax.annotation.Nullable String steamid) {
    this.steamid = steamid;
  }


  public GetGameSteamSummary200Response timecreated(@javax.annotation.Nullable Integer timecreated) {
    this.timecreated = timecreated;
    return this;
  }

  /**
   * 账户创建时的Unix时间戳（秒）。
   * @return timecreated
   */
  @javax.annotation.Nullable
  public Integer getTimecreated() {
    return timecreated;
  }

  public void setTimecreated(@javax.annotation.Nullable Integer timecreated) {
    this.timecreated = timecreated;
  }


  public GetGameSteamSummary200Response timecreatedStr(@javax.annotation.Nullable String timecreatedStr) {
    this.timecreatedStr = timecreatedStr;
    return this;
  }

  /**
   * 我们为你格式化好的账户创建时间，更直观。
   * @return timecreatedStr
   */
  @javax.annotation.Nullable
  public String getTimecreatedStr() {
    return timecreatedStr;
  }

  public void setTimecreatedStr(@javax.annotation.Nullable String timecreatedStr) {
    this.timecreatedStr = timecreatedStr;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetGameSteamSummary200Response getGameSteamSummary200Response = (GetGameSteamSummary200Response) o;
    return Objects.equals(this.avatar, getGameSteamSummary200Response.avatar) &&
        Objects.equals(this.avatarfull, getGameSteamSummary200Response.avatarfull) &&
        Objects.equals(this.avatarmedium, getGameSteamSummary200Response.avatarmedium) &&
        Objects.equals(this.code, getGameSteamSummary200Response.code) &&
        Objects.equals(this.communityvisibilitystate, getGameSteamSummary200Response.communityvisibilitystate) &&
        Objects.equals(this.loccountrycode, getGameSteamSummary200Response.loccountrycode) &&
        Objects.equals(this.personaname, getGameSteamSummary200Response.personaname) &&
        Objects.equals(this.personastate, getGameSteamSummary200Response.personastate) &&
        Objects.equals(this.primaryclanid, getGameSteamSummary200Response.primaryclanid) &&
        Objects.equals(this.profilestate, getGameSteamSummary200Response.profilestate) &&
        Objects.equals(this.profileurl, getGameSteamSummary200Response.profileurl) &&
        Objects.equals(this.realname, getGameSteamSummary200Response.realname) &&
        Objects.equals(this.steamid, getGameSteamSummary200Response.steamid) &&
        Objects.equals(this.timecreated, getGameSteamSummary200Response.timecreated) &&
        Objects.equals(this.timecreatedStr, getGameSteamSummary200Response.timecreatedStr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(avatar, avatarfull, avatarmedium, code, communityvisibilitystate, loccountrycode, personaname, personastate, primaryclanid, profilestate, profileurl, realname, steamid, timecreated, timecreatedStr);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetGameSteamSummary200Response {\n");
    sb.append("    avatar: ").append(toIndentedString(avatar)).append("\n");
    sb.append("    avatarfull: ").append(toIndentedString(avatarfull)).append("\n");
    sb.append("    avatarmedium: ").append(toIndentedString(avatarmedium)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    communityvisibilitystate: ").append(toIndentedString(communityvisibilitystate)).append("\n");
    sb.append("    loccountrycode: ").append(toIndentedString(loccountrycode)).append("\n");
    sb.append("    personaname: ").append(toIndentedString(personaname)).append("\n");
    sb.append("    personastate: ").append(toIndentedString(personastate)).append("\n");
    sb.append("    primaryclanid: ").append(toIndentedString(primaryclanid)).append("\n");
    sb.append("    profilestate: ").append(toIndentedString(profilestate)).append("\n");
    sb.append("    profileurl: ").append(toIndentedString(profileurl)).append("\n");
    sb.append("    realname: ").append(toIndentedString(realname)).append("\n");
    sb.append("    steamid: ").append(toIndentedString(steamid)).append("\n");
    sb.append("    timecreated: ").append(toIndentedString(timecreated)).append("\n");
    sb.append("    timecreatedStr: ").append(toIndentedString(timecreatedStr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("avatar", "avatarfull", "avatarmedium", "code", "communityvisibilitystate", "loccountrycode", "personaname", "personastate", "primaryclanid", "profilestate", "profileurl", "realname", "steamid", "timecreated", "timecreated_str"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetGameSteamSummary200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetGameSteamSummary200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetGameSteamSummary200Response is not found in the empty JSON string", GetGameSteamSummary200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetGameSteamSummary200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetGameSteamSummary200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("avatar") != null && !jsonObj.get("avatar").isJsonNull()) && !jsonObj.get("avatar").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `avatar` to be a primitive type in the JSON string but got `%s`", jsonObj.get("avatar").toString()));
      }
      if ((jsonObj.get("avatarfull") != null && !jsonObj.get("avatarfull").isJsonNull()) && !jsonObj.get("avatarfull").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `avatarfull` to be a primitive type in the JSON string but got `%s`", jsonObj.get("avatarfull").toString()));
      }
      if ((jsonObj.get("avatarmedium") != null && !jsonObj.get("avatarmedium").isJsonNull()) && !jsonObj.get("avatarmedium").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `avatarmedium` to be a primitive type in the JSON string but got `%s`", jsonObj.get("avatarmedium").toString()));
      }
      if ((jsonObj.get("loccountrycode") != null && !jsonObj.get("loccountrycode").isJsonNull()) && !jsonObj.get("loccountrycode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `loccountrycode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("loccountrycode").toString()));
      }
      if ((jsonObj.get("personaname") != null && !jsonObj.get("personaname").isJsonNull()) && !jsonObj.get("personaname").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `personaname` to be a primitive type in the JSON string but got `%s`", jsonObj.get("personaname").toString()));
      }
      if ((jsonObj.get("primaryclanid") != null && !jsonObj.get("primaryclanid").isJsonNull()) && !jsonObj.get("primaryclanid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `primaryclanid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("primaryclanid").toString()));
      }
      if ((jsonObj.get("profileurl") != null && !jsonObj.get("profileurl").isJsonNull()) && !jsonObj.get("profileurl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `profileurl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("profileurl").toString()));
      }
      if ((jsonObj.get("realname") != null && !jsonObj.get("realname").isJsonNull()) && !jsonObj.get("realname").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `realname` to be a primitive type in the JSON string but got `%s`", jsonObj.get("realname").toString()));
      }
      if ((jsonObj.get("steamid") != null && !jsonObj.get("steamid").isJsonNull()) && !jsonObj.get("steamid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `steamid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("steamid").toString()));
      }
      if ((jsonObj.get("timecreated_str") != null && !jsonObj.get("timecreated_str").isJsonNull()) && !jsonObj.get("timecreated_str").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `timecreated_str` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timecreated_str").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetGameSteamSummary200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetGameSteamSummary200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetGameSteamSummary200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetGameSteamSummary200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<GetGameSteamSummary200Response>() {
           @Override
           public void write(JsonWriter out, GetGameSteamSummary200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetGameSteamSummary200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetGameSteamSummary200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetGameSteamSummary200Response
   * @throws IOException if the JSON string is invalid with respect to GetGameSteamSummary200Response
   */
  public static GetGameSteamSummary200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetGameSteamSummary200Response.class);
  }

  /**
   * Convert an instance of GetGameSteamSummary200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

