/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * GetHistoryProgrammer200ResponseEventsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-11T15:37:17.258797600+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class GetHistoryProgrammer200ResponseEventsInner {
  public static final String SERIALIZED_NAME_YEAR = "year";
  @SerializedName(SERIALIZED_NAME_YEAR)
  @javax.annotation.Nullable
  private Integer year;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  @javax.annotation.Nullable
  private String category;

  public static final String SERIALIZED_NAME_IMPORTANCE = "importance";
  @SerializedName(SERIALIZED_NAME_IMPORTANCE)
  @javax.annotation.Nullable
  private Integer importance;

  public static final String SERIALIZED_NAME_RELEVANCE_SCORE = "relevance_score";
  @SerializedName(SERIALIZED_NAME_RELEVANCE_SCORE)
  @javax.annotation.Nullable
  private BigDecimal relevanceScore;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nullable
  private String url;

  public GetHistoryProgrammer200ResponseEventsInner() {
  }

  public GetHistoryProgrammer200ResponseEventsInner year(@javax.annotation.Nullable Integer year) {
    this.year = year;
    return this;
  }

  /**
   * Get year
   * @return year
   */
  @javax.annotation.Nullable
  public Integer getYear() {
    return year;
  }

  public void setYear(@javax.annotation.Nullable Integer year) {
    this.year = year;
  }


  public GetHistoryProgrammer200ResponseEventsInner title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public GetHistoryProgrammer200ResponseEventsInner description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public GetHistoryProgrammer200ResponseEventsInner category(@javax.annotation.Nullable String category) {
    this.category = category;
    return this;
  }

  /**
   * Get category
   * @return category
   */
  @javax.annotation.Nullable
  public String getCategory() {
    return category;
  }

  public void setCategory(@javax.annotation.Nullable String category) {
    this.category = category;
  }


  public GetHistoryProgrammer200ResponseEventsInner importance(@javax.annotation.Nullable Integer importance) {
    this.importance = importance;
    return this;
  }

  /**
   * Get importance
   * @return importance
   */
  @javax.annotation.Nullable
  public Integer getImportance() {
    return importance;
  }

  public void setImportance(@javax.annotation.Nullable Integer importance) {
    this.importance = importance;
  }


  public GetHistoryProgrammer200ResponseEventsInner relevanceScore(@javax.annotation.Nullable BigDecimal relevanceScore) {
    this.relevanceScore = relevanceScore;
    return this;
  }

  /**
   * Get relevanceScore
   * @return relevanceScore
   */
  @javax.annotation.Nullable
  public BigDecimal getRelevanceScore() {
    return relevanceScore;
  }

  public void setRelevanceScore(@javax.annotation.Nullable BigDecimal relevanceScore) {
    this.relevanceScore = relevanceScore;
  }


  public GetHistoryProgrammer200ResponseEventsInner url(@javax.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nullable
  public String getUrl() {
    return url;
  }

  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetHistoryProgrammer200ResponseEventsInner getHistoryProgrammer200ResponseEventsInner = (GetHistoryProgrammer200ResponseEventsInner) o;
    return Objects.equals(this.year, getHistoryProgrammer200ResponseEventsInner.year) &&
        Objects.equals(this.title, getHistoryProgrammer200ResponseEventsInner.title) &&
        Objects.equals(this.description, getHistoryProgrammer200ResponseEventsInner.description) &&
        Objects.equals(this.category, getHistoryProgrammer200ResponseEventsInner.category) &&
        Objects.equals(this.importance, getHistoryProgrammer200ResponseEventsInner.importance) &&
        Objects.equals(this.relevanceScore, getHistoryProgrammer200ResponseEventsInner.relevanceScore) &&
        Objects.equals(this.url, getHistoryProgrammer200ResponseEventsInner.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(year, title, description, category, importance, relevanceScore, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetHistoryProgrammer200ResponseEventsInner {\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    importance: ").append(toIndentedString(importance)).append("\n");
    sb.append("    relevanceScore: ").append(toIndentedString(relevanceScore)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("year", "title", "description", "category", "importance", "relevance_score", "url"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetHistoryProgrammer200ResponseEventsInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetHistoryProgrammer200ResponseEventsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetHistoryProgrammer200ResponseEventsInner is not found in the empty JSON string", GetHistoryProgrammer200ResponseEventsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetHistoryProgrammer200ResponseEventsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetHistoryProgrammer200ResponseEventsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull()) && !jsonObj.get("category").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `category` to be a primitive type in the JSON string but got `%s`", jsonObj.get("category").toString()));
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetHistoryProgrammer200ResponseEventsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetHistoryProgrammer200ResponseEventsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetHistoryProgrammer200ResponseEventsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetHistoryProgrammer200ResponseEventsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<GetHistoryProgrammer200ResponseEventsInner>() {
           @Override
           public void write(JsonWriter out, GetHistoryProgrammer200ResponseEventsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetHistoryProgrammer200ResponseEventsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetHistoryProgrammer200ResponseEventsInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetHistoryProgrammer200ResponseEventsInner
   * @throws IOException if the JSON string is invalid with respect to GetHistoryProgrammer200ResponseEventsInner
   */
  public static GetHistoryProgrammer200ResponseEventsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetHistoryProgrammer200ResponseEventsInner.class);
  }

  /**
   * Convert an instance of GetHistoryProgrammer200ResponseEventsInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

