/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * 统计摘要。
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-12T12:48:58.845719500+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class GetMiscHolidayCalendar200ResponseSummary {
  public static final String SERIALIZED_NAME_TOTAL_DAYS = "total_days";
  @SerializedName(SERIALIZED_NAME_TOTAL_DAYS)
  @javax.annotation.Nullable
  private Integer totalDays;

  public static final String SERIALIZED_NAME_WEEKEND_DAYS = "weekend_days";
  @SerializedName(SERIALIZED_NAME_WEEKEND_DAYS)
  @javax.annotation.Nullable
  private Integer weekendDays;

  public static final String SERIALIZED_NAME_WORKDAYS = "workdays";
  @SerializedName(SERIALIZED_NAME_WORKDAYS)
  @javax.annotation.Nullable
  private Integer workdays;

  public static final String SERIALIZED_NAME_REST_DAYS = "rest_days";
  @SerializedName(SERIALIZED_NAME_REST_DAYS)
  @javax.annotation.Nullable
  private Integer restDays;

  public static final String SERIALIZED_NAME_HOLIDAY_EVENTS = "holiday_events";
  @SerializedName(SERIALIZED_NAME_HOLIDAY_EVENTS)
  @javax.annotation.Nullable
  private Integer holidayEvents;

  public static final String SERIALIZED_NAME_LEGAL_REST_DAYS = "legal_rest_days";
  @SerializedName(SERIALIZED_NAME_LEGAL_REST_DAYS)
  @javax.annotation.Nullable
  private Integer legalRestDays;

  public static final String SERIALIZED_NAME_LEGAL_WORKDAYS = "legal_workdays";
  @SerializedName(SERIALIZED_NAME_LEGAL_WORKDAYS)
  @javax.annotation.Nullable
  private Integer legalWorkdays;

  public GetMiscHolidayCalendar200ResponseSummary() {
  }

  public GetMiscHolidayCalendar200ResponseSummary totalDays(@javax.annotation.Nullable Integer totalDays) {
    this.totalDays = totalDays;
    return this;
  }

  /**
   * 查询范围内总天数。
   * @return totalDays
   */
  @javax.annotation.Nullable
  public Integer getTotalDays() {
    return totalDays;
  }

  public void setTotalDays(@javax.annotation.Nullable Integer totalDays) {
    this.totalDays = totalDays;
  }


  public GetMiscHolidayCalendar200ResponseSummary weekendDays(@javax.annotation.Nullable Integer weekendDays) {
    this.weekendDays = weekendDays;
    return this;
  }

  /**
   * 查询范围内周末天数。
   * @return weekendDays
   */
  @javax.annotation.Nullable
  public Integer getWeekendDays() {
    return weekendDays;
  }

  public void setWeekendDays(@javax.annotation.Nullable Integer weekendDays) {
    this.weekendDays = weekendDays;
  }


  public GetMiscHolidayCalendar200ResponseSummary workdays(@javax.annotation.Nullable Integer workdays) {
    this.workdays = workdays;
    return this;
  }

  /**
   * 查询范围内工作日天数（含法定调休上班）。
   * @return workdays
   */
  @javax.annotation.Nullable
  public Integer getWorkdays() {
    return workdays;
  }

  public void setWorkdays(@javax.annotation.Nullable Integer workdays) {
    this.workdays = workdays;
  }


  public GetMiscHolidayCalendar200ResponseSummary restDays(@javax.annotation.Nullable Integer restDays) {
    this.restDays = restDays;
    return this;
  }

  /**
   * 查询范围内休息日天数（含周末和法定休假）。
   * @return restDays
   */
  @javax.annotation.Nullable
  public Integer getRestDays() {
    return restDays;
  }

  public void setRestDays(@javax.annotation.Nullable Integer restDays) {
    this.restDays = restDays;
  }


  public GetMiscHolidayCalendar200ResponseSummary holidayEvents(@javax.annotation.Nullable Integer holidayEvents) {
    this.holidayEvents = holidayEvents;
    return this;
  }

  /**
   * 按 holiday_type 过滤后的节日事件总数。
   * @return holidayEvents
   */
  @javax.annotation.Nullable
  public Integer getHolidayEvents() {
    return holidayEvents;
  }

  public void setHolidayEvents(@javax.annotation.Nullable Integer holidayEvents) {
    this.holidayEvents = holidayEvents;
  }


  public GetMiscHolidayCalendar200ResponseSummary legalRestDays(@javax.annotation.Nullable Integer legalRestDays) {
    this.legalRestDays = legalRestDays;
    return this;
  }

  /**
   * 法定休假日天数。
   * @return legalRestDays
   */
  @javax.annotation.Nullable
  public Integer getLegalRestDays() {
    return legalRestDays;
  }

  public void setLegalRestDays(@javax.annotation.Nullable Integer legalRestDays) {
    this.legalRestDays = legalRestDays;
  }


  public GetMiscHolidayCalendar200ResponseSummary legalWorkdays(@javax.annotation.Nullable Integer legalWorkdays) {
    this.legalWorkdays = legalWorkdays;
    return this;
  }

  /**
   * 法定调休上班天数。
   * @return legalWorkdays
   */
  @javax.annotation.Nullable
  public Integer getLegalWorkdays() {
    return legalWorkdays;
  }

  public void setLegalWorkdays(@javax.annotation.Nullable Integer legalWorkdays) {
    this.legalWorkdays = legalWorkdays;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMiscHolidayCalendar200ResponseSummary getMiscHolidayCalendar200ResponseSummary = (GetMiscHolidayCalendar200ResponseSummary) o;
    return Objects.equals(this.totalDays, getMiscHolidayCalendar200ResponseSummary.totalDays) &&
        Objects.equals(this.weekendDays, getMiscHolidayCalendar200ResponseSummary.weekendDays) &&
        Objects.equals(this.workdays, getMiscHolidayCalendar200ResponseSummary.workdays) &&
        Objects.equals(this.restDays, getMiscHolidayCalendar200ResponseSummary.restDays) &&
        Objects.equals(this.holidayEvents, getMiscHolidayCalendar200ResponseSummary.holidayEvents) &&
        Objects.equals(this.legalRestDays, getMiscHolidayCalendar200ResponseSummary.legalRestDays) &&
        Objects.equals(this.legalWorkdays, getMiscHolidayCalendar200ResponseSummary.legalWorkdays);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalDays, weekendDays, workdays, restDays, holidayEvents, legalRestDays, legalWorkdays);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMiscHolidayCalendar200ResponseSummary {\n");
    sb.append("    totalDays: ").append(toIndentedString(totalDays)).append("\n");
    sb.append("    weekendDays: ").append(toIndentedString(weekendDays)).append("\n");
    sb.append("    workdays: ").append(toIndentedString(workdays)).append("\n");
    sb.append("    restDays: ").append(toIndentedString(restDays)).append("\n");
    sb.append("    holidayEvents: ").append(toIndentedString(holidayEvents)).append("\n");
    sb.append("    legalRestDays: ").append(toIndentedString(legalRestDays)).append("\n");
    sb.append("    legalWorkdays: ").append(toIndentedString(legalWorkdays)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("total_days", "weekend_days", "workdays", "rest_days", "holiday_events", "legal_rest_days", "legal_workdays"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetMiscHolidayCalendar200ResponseSummary
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetMiscHolidayCalendar200ResponseSummary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetMiscHolidayCalendar200ResponseSummary is not found in the empty JSON string", GetMiscHolidayCalendar200ResponseSummary.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetMiscHolidayCalendar200ResponseSummary.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetMiscHolidayCalendar200ResponseSummary` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetMiscHolidayCalendar200ResponseSummary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetMiscHolidayCalendar200ResponseSummary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetMiscHolidayCalendar200ResponseSummary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetMiscHolidayCalendar200ResponseSummary.class));

       return (TypeAdapter<T>) new TypeAdapter<GetMiscHolidayCalendar200ResponseSummary>() {
           @Override
           public void write(JsonWriter out, GetMiscHolidayCalendar200ResponseSummary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetMiscHolidayCalendar200ResponseSummary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetMiscHolidayCalendar200ResponseSummary given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetMiscHolidayCalendar200ResponseSummary
   * @throws IOException if the JSON string is invalid with respect to GetMiscHolidayCalendar200ResponseSummary
   */
  public static GetMiscHolidayCalendar200ResponseSummary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetMiscHolidayCalendar200ResponseSummary.class);
  }

  /**
   * Convert an instance of GetMiscHolidayCalendar200ResponseSummary to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

