/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GetMiscHolidayCalendar200ResponseNearbyNextInnerEventsInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * GetMiscHolidayCalendar200ResponseNearbyNextInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-12T12:48:58.845719500+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class GetMiscHolidayCalendar200ResponseNearbyNextInner {
  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  @javax.annotation.Nullable
  private String date;

  public static final String SERIALIZED_NAME_EVENTS = "events";
  @SerializedName(SERIALIZED_NAME_EVENTS)
  @javax.annotation.Nullable
  private List<GetMiscHolidayCalendar200ResponseNearbyNextInnerEventsInner> events = new ArrayList<>();

  public GetMiscHolidayCalendar200ResponseNearbyNextInner() {
  }

  public GetMiscHolidayCalendar200ResponseNearbyNextInner date(@javax.annotation.Nullable String date) {
    this.date = date;
    return this;
  }

  /**
   * 聚合日期。
   * @return date
   */
  @javax.annotation.Nullable
  public String getDate() {
    return date;
  }

  public void setDate(@javax.annotation.Nullable String date) {
    this.date = date;
  }


  public GetMiscHolidayCalendar200ResponseNearbyNextInner events(@javax.annotation.Nullable List<GetMiscHolidayCalendar200ResponseNearbyNextInnerEventsInner> events) {
    this.events = events;
    return this;
  }

  public GetMiscHolidayCalendar200ResponseNearbyNextInner addEventsItem(GetMiscHolidayCalendar200ResponseNearbyNextInnerEventsInner eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<>();
    }
    this.events.add(eventsItem);
    return this;
  }

  /**
   * 该日期上的节日事件列表。
   * @return events
   */
  @javax.annotation.Nullable
  public List<GetMiscHolidayCalendar200ResponseNearbyNextInnerEventsInner> getEvents() {
    return events;
  }

  public void setEvents(@javax.annotation.Nullable List<GetMiscHolidayCalendar200ResponseNearbyNextInnerEventsInner> events) {
    this.events = events;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMiscHolidayCalendar200ResponseNearbyNextInner getMiscHolidayCalendar200ResponseNearbyNextInner = (GetMiscHolidayCalendar200ResponseNearbyNextInner) o;
    return Objects.equals(this.date, getMiscHolidayCalendar200ResponseNearbyNextInner.date) &&
        Objects.equals(this.events, getMiscHolidayCalendar200ResponseNearbyNextInner.events);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, events);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMiscHolidayCalendar200ResponseNearbyNextInner {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("date", "events"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetMiscHolidayCalendar200ResponseNearbyNextInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetMiscHolidayCalendar200ResponseNearbyNextInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetMiscHolidayCalendar200ResponseNearbyNextInner is not found in the empty JSON string", GetMiscHolidayCalendar200ResponseNearbyNextInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetMiscHolidayCalendar200ResponseNearbyNextInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetMiscHolidayCalendar200ResponseNearbyNextInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("date") != null && !jsonObj.get("date").isJsonNull()) && !jsonObj.get("date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date").toString()));
      }
      if (jsonObj.get("events") != null && !jsonObj.get("events").isJsonNull()) {
        JsonArray jsonArrayevents = jsonObj.getAsJsonArray("events");
        if (jsonArrayevents != null) {
          // ensure the json data is an array
          if (!jsonObj.get("events").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `events` to be an array in the JSON string but got `%s`", jsonObj.get("events").toString()));
          }

          // validate the optional field `events` (array)
          for (int i = 0; i < jsonArrayevents.size(); i++) {
            GetMiscHolidayCalendar200ResponseNearbyNextInnerEventsInner.validateJsonElement(jsonArrayevents.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetMiscHolidayCalendar200ResponseNearbyNextInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetMiscHolidayCalendar200ResponseNearbyNextInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetMiscHolidayCalendar200ResponseNearbyNextInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetMiscHolidayCalendar200ResponseNearbyNextInner.class));

       return (TypeAdapter<T>) new TypeAdapter<GetMiscHolidayCalendar200ResponseNearbyNextInner>() {
           @Override
           public void write(JsonWriter out, GetMiscHolidayCalendar200ResponseNearbyNextInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetMiscHolidayCalendar200ResponseNearbyNextInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetMiscHolidayCalendar200ResponseNearbyNextInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetMiscHolidayCalendar200ResponseNearbyNextInner
   * @throws IOException if the JSON string is invalid with respect to GetMiscHolidayCalendar200ResponseNearbyNextInner
   */
  public static GetMiscHolidayCalendar200ResponseNearbyNextInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetMiscHolidayCalendar200ResponseNearbyNextInner.class);
  }

  /**
   * Convert an instance of GetMiscHolidayCalendar200ResponseNearbyNextInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

