/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.GetMiscDistrict200ResponseResultsInnerCenter;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * GetMiscDistrict200ResponseResultsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T17:21:00.573689900+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class GetMiscDistrict200ResponseResultsInner {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_LEVEL = "level";
  @SerializedName(SERIALIZED_NAME_LEVEL)
  @javax.annotation.Nullable
  private String level;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  @javax.annotation.Nullable
  private String country;

  public static final String SERIALIZED_NAME_COUNTRY_CODE = "country_code";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  @javax.annotation.Nullable
  private String countryCode;

  public static final String SERIALIZED_NAME_PROVINCE = "province";
  @SerializedName(SERIALIZED_NAME_PROVINCE)
  @javax.annotation.Nullable
  private String province;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  @javax.annotation.Nullable
  private String city;

  public static final String SERIALIZED_NAME_DISTRICT = "district";
  @SerializedName(SERIALIZED_NAME_DISTRICT)
  @javax.annotation.Nullable
  private String district;

  public static final String SERIALIZED_NAME_STREET = "street";
  @SerializedName(SERIALIZED_NAME_STREET)
  @javax.annotation.Nullable
  private String street;

  public static final String SERIALIZED_NAME_ADCODE = "adcode";
  @SerializedName(SERIALIZED_NAME_ADCODE)
  @javax.annotation.Nullable
  private String adcode;

  public static final String SERIALIZED_NAME_CITYCODE = "citycode";
  @SerializedName(SERIALIZED_NAME_CITYCODE)
  @javax.annotation.Nullable
  private String citycode;

  public static final String SERIALIZED_NAME_CENTER = "center";
  @SerializedName(SERIALIZED_NAME_CENTER)
  @javax.annotation.Nullable
  private GetMiscDistrict200ResponseResultsInnerCenter center;

  public static final String SERIALIZED_NAME_POPULATION = "population";
  @SerializedName(SERIALIZED_NAME_POPULATION)
  @javax.annotation.Nullable
  private Integer population;

  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  @javax.annotation.Nullable
  private String timezone;

  public GetMiscDistrict200ResponseResultsInner() {
  }

  public GetMiscDistrict200ResponseResultsInner name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * 地区名称。
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public GetMiscDistrict200ResponseResultsInner level(@javax.annotation.Nullable String level) {
    this.level = level;
    return this;
  }

  /**
   * 行政级别：province / city / district / street。
   * @return level
   */
  @javax.annotation.Nullable
  public String getLevel() {
    return level;
  }

  public void setLevel(@javax.annotation.Nullable String level) {
    this.level = level;
  }


  public GetMiscDistrict200ResponseResultsInner country(@javax.annotation.Nullable String country) {
    this.country = country;
    return this;
  }

  /**
   * 国家名称。
   * @return country
   */
  @javax.annotation.Nullable
  public String getCountry() {
    return country;
  }

  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }


  public GetMiscDistrict200ResponseResultsInner countryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  /**
   * ISO 3166-1 alpha-2 国家代码。
   * @return countryCode
   */
  @javax.annotation.Nullable
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
  }


  public GetMiscDistrict200ResponseResultsInner province(@javax.annotation.Nullable String province) {
    this.province = province;
    return this;
  }

  /**
   * 省/州（中国数据）或一级行政区（国际数据）。
   * @return province
   */
  @javax.annotation.Nullable
  public String getProvince() {
    return province;
  }

  public void setProvince(@javax.annotation.Nullable String province) {
    this.province = province;
  }


  public GetMiscDistrict200ResponseResultsInner city(@javax.annotation.Nullable String city) {
    this.city = city;
    return this;
  }

  /**
   * 市（仅中国数据）。
   * @return city
   */
  @javax.annotation.Nullable
  public String getCity() {
    return city;
  }

  public void setCity(@javax.annotation.Nullable String city) {
    this.city = city;
  }


  public GetMiscDistrict200ResponseResultsInner district(@javax.annotation.Nullable String district) {
    this.district = district;
    return this;
  }

  /**
   * 区/县（仅中国数据）。
   * @return district
   */
  @javax.annotation.Nullable
  public String getDistrict() {
    return district;
  }

  public void setDistrict(@javax.annotation.Nullable String district) {
    this.district = district;
  }


  public GetMiscDistrict200ResponseResultsInner street(@javax.annotation.Nullable String street) {
    this.street = street;
    return this;
  }

  /**
   * 街道/乡镇（仅中国数据）。
   * @return street
   */
  @javax.annotation.Nullable
  public String getStreet() {
    return street;
  }

  public void setStreet(@javax.annotation.Nullable String street) {
    this.street = street;
  }


  public GetMiscDistrict200ResponseResultsInner adcode(@javax.annotation.Nullable String adcode) {
    this.adcode = adcode;
    return this;
  }

  /**
   * 行政区划代码（仅中国数据）。
   * @return adcode
   */
  @javax.annotation.Nullable
  public String getAdcode() {
    return adcode;
  }

  public void setAdcode(@javax.annotation.Nullable String adcode) {
    this.adcode = adcode;
  }


  public GetMiscDistrict200ResponseResultsInner citycode(@javax.annotation.Nullable String citycode) {
    this.citycode = citycode;
    return this;
  }

  /**
   * 城市区号（仅中国数据）。
   * @return citycode
   */
  @javax.annotation.Nullable
  public String getCitycode() {
    return citycode;
  }

  public void setCitycode(@javax.annotation.Nullable String citycode) {
    this.citycode = citycode;
  }


  public GetMiscDistrict200ResponseResultsInner center(@javax.annotation.Nullable GetMiscDistrict200ResponseResultsInnerCenter center) {
    this.center = center;
    return this;
  }

  /**
   * Get center
   * @return center
   */
  @javax.annotation.Nullable
  public GetMiscDistrict200ResponseResultsInnerCenter getCenter() {
    return center;
  }

  public void setCenter(@javax.annotation.Nullable GetMiscDistrict200ResponseResultsInnerCenter center) {
    this.center = center;
  }


  public GetMiscDistrict200ResponseResultsInner population(@javax.annotation.Nullable Integer population) {
    this.population = population;
    return this;
  }

  /**
   * 人口（仅国际城市数据）。
   * @return population
   */
  @javax.annotation.Nullable
  public Integer getPopulation() {
    return population;
  }

  public void setPopulation(@javax.annotation.Nullable Integer population) {
    this.population = population;
  }


  public GetMiscDistrict200ResponseResultsInner timezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * 时区（仅国际城市数据），如 Asia/Tokyo。
   * @return timezone
   */
  @javax.annotation.Nullable
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMiscDistrict200ResponseResultsInner getMiscDistrict200ResponseResultsInner = (GetMiscDistrict200ResponseResultsInner) o;
    return Objects.equals(this.name, getMiscDistrict200ResponseResultsInner.name) &&
        Objects.equals(this.level, getMiscDistrict200ResponseResultsInner.level) &&
        Objects.equals(this.country, getMiscDistrict200ResponseResultsInner.country) &&
        Objects.equals(this.countryCode, getMiscDistrict200ResponseResultsInner.countryCode) &&
        Objects.equals(this.province, getMiscDistrict200ResponseResultsInner.province) &&
        Objects.equals(this.city, getMiscDistrict200ResponseResultsInner.city) &&
        Objects.equals(this.district, getMiscDistrict200ResponseResultsInner.district) &&
        Objects.equals(this.street, getMiscDistrict200ResponseResultsInner.street) &&
        Objects.equals(this.adcode, getMiscDistrict200ResponseResultsInner.adcode) &&
        Objects.equals(this.citycode, getMiscDistrict200ResponseResultsInner.citycode) &&
        Objects.equals(this.center, getMiscDistrict200ResponseResultsInner.center) &&
        Objects.equals(this.population, getMiscDistrict200ResponseResultsInner.population) &&
        Objects.equals(this.timezone, getMiscDistrict200ResponseResultsInner.timezone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, level, country, countryCode, province, city, district, street, adcode, citycode, center, population, timezone);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMiscDistrict200ResponseResultsInner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    province: ").append(toIndentedString(province)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    adcode: ").append(toIndentedString(adcode)).append("\n");
    sb.append("    citycode: ").append(toIndentedString(citycode)).append("\n");
    sb.append("    center: ").append(toIndentedString(center)).append("\n");
    sb.append("    population: ").append(toIndentedString(population)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "level", "country", "country_code", "province", "city", "district", "street", "adcode", "citycode", "center", "population", "timezone"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetMiscDistrict200ResponseResultsInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetMiscDistrict200ResponseResultsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetMiscDistrict200ResponseResultsInner is not found in the empty JSON string", GetMiscDistrict200ResponseResultsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetMiscDistrict200ResponseResultsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetMiscDistrict200ResponseResultsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("level") != null && !jsonObj.get("level").isJsonNull()) && !jsonObj.get("level").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `level` to be a primitive type in the JSON string but got `%s`", jsonObj.get("level").toString()));
      }
      if ((jsonObj.get("country") != null && !jsonObj.get("country").isJsonNull()) && !jsonObj.get("country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country").toString()));
      }
      if ((jsonObj.get("country_code") != null && !jsonObj.get("country_code").isJsonNull()) && !jsonObj.get("country_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `country_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country_code").toString()));
      }
      if ((jsonObj.get("province") != null && !jsonObj.get("province").isJsonNull()) && !jsonObj.get("province").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `province` to be a primitive type in the JSON string but got `%s`", jsonObj.get("province").toString()));
      }
      if ((jsonObj.get("city") != null && !jsonObj.get("city").isJsonNull()) && !jsonObj.get("city").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `city` to be a primitive type in the JSON string but got `%s`", jsonObj.get("city").toString()));
      }
      if ((jsonObj.get("district") != null && !jsonObj.get("district").isJsonNull()) && !jsonObj.get("district").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `district` to be a primitive type in the JSON string but got `%s`", jsonObj.get("district").toString()));
      }
      if ((jsonObj.get("street") != null && !jsonObj.get("street").isJsonNull()) && !jsonObj.get("street").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `street` to be a primitive type in the JSON string but got `%s`", jsonObj.get("street").toString()));
      }
      if ((jsonObj.get("adcode") != null && !jsonObj.get("adcode").isJsonNull()) && !jsonObj.get("adcode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `adcode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("adcode").toString()));
      }
      if ((jsonObj.get("citycode") != null && !jsonObj.get("citycode").isJsonNull()) && !jsonObj.get("citycode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `citycode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("citycode").toString()));
      }
      // validate the optional field `center`
      if (jsonObj.get("center") != null && !jsonObj.get("center").isJsonNull()) {
        GetMiscDistrict200ResponseResultsInnerCenter.validateJsonElement(jsonObj.get("center"));
      }
      if ((jsonObj.get("timezone") != null && !jsonObj.get("timezone").isJsonNull()) && !jsonObj.get("timezone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `timezone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timezone").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetMiscDistrict200ResponseResultsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetMiscDistrict200ResponseResultsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetMiscDistrict200ResponseResultsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetMiscDistrict200ResponseResultsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<GetMiscDistrict200ResponseResultsInner>() {
           @Override
           public void write(JsonWriter out, GetMiscDistrict200ResponseResultsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetMiscDistrict200ResponseResultsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetMiscDistrict200ResponseResultsInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetMiscDistrict200ResponseResultsInner
   * @throws IOException if the JSON string is invalid with respect to GetMiscDistrict200ResponseResultsInner
   */
  public static GetMiscDistrict200ResponseResultsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetMiscDistrict200ResponseResultsInner.class);
  }

  /**
   * Convert an instance of GetMiscDistrict200ResponseResultsInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

