/*
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * GetMiscWeather200ResponseHourlyForecastInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-15T11:28:35.443476300+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class GetMiscWeather200ResponseHourlyForecastInner {
  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  @javax.annotation.Nullable
  private String time;

  public static final String SERIALIZED_NAME_TEMPERATURE = "temperature";
  @SerializedName(SERIALIZED_NAME_TEMPERATURE)
  @javax.annotation.Nullable
  private BigDecimal temperature;

  public static final String SERIALIZED_NAME_WEATHER = "weather";
  @SerializedName(SERIALIZED_NAME_WEATHER)
  @javax.annotation.Nullable
  private String weather;

  public static final String SERIALIZED_NAME_WIND_DIRECTION = "wind_direction";
  @SerializedName(SERIALIZED_NAME_WIND_DIRECTION)
  @javax.annotation.Nullable
  private String windDirection;

  public static final String SERIALIZED_NAME_WIND_SPEED = "wind_speed";
  @SerializedName(SERIALIZED_NAME_WIND_SPEED)
  @javax.annotation.Nullable
  private BigDecimal windSpeed;

  public static final String SERIALIZED_NAME_WIND_SCALE = "wind_scale";
  @SerializedName(SERIALIZED_NAME_WIND_SCALE)
  @javax.annotation.Nullable
  private String windScale;

  public static final String SERIALIZED_NAME_HUMIDITY = "humidity";
  @SerializedName(SERIALIZED_NAME_HUMIDITY)
  @javax.annotation.Nullable
  private BigDecimal humidity;

  public static final String SERIALIZED_NAME_PRECIP = "precip";
  @SerializedName(SERIALIZED_NAME_PRECIP)
  @javax.annotation.Nullable
  private BigDecimal precip;

  public static final String SERIALIZED_NAME_FEELS_LIKE = "feels_like";
  @SerializedName(SERIALIZED_NAME_FEELS_LIKE)
  @javax.annotation.Nullable
  private BigDecimal feelsLike;

  public static final String SERIALIZED_NAME_VISIBILITY = "visibility";
  @SerializedName(SERIALIZED_NAME_VISIBILITY)
  @javax.annotation.Nullable
  private BigDecimal visibility;

  public static final String SERIALIZED_NAME_POP = "pop";
  @SerializedName(SERIALIZED_NAME_POP)
  @javax.annotation.Nullable
  private BigDecimal pop;

  public static final String SERIALIZED_NAME_UV_INDEX = "uv_index";
  @SerializedName(SERIALIZED_NAME_UV_INDEX)
  @javax.annotation.Nullable
  private BigDecimal uvIndex;

  public GetMiscWeather200ResponseHourlyForecastInner() {
  }

  public GetMiscWeather200ResponseHourlyForecastInner time(@javax.annotation.Nullable String time) {
    this.time = time;
    return this;
  }

  /**
   * 预报时间（ISO8601 或 YYYY-MM-DD HH:MM）
   * @return time
   */
  @javax.annotation.Nullable
  public String getTime() {
    return time;
  }

  public void setTime(@javax.annotation.Nullable String time) {
    this.time = time;
  }


  public GetMiscWeather200ResponseHourlyForecastInner temperature(@javax.annotation.Nullable BigDecimal temperature) {
    this.temperature = temperature;
    return this;
  }

  /**
   * 温度 °C
   * @return temperature
   */
  @javax.annotation.Nullable
  public BigDecimal getTemperature() {
    return temperature;
  }

  public void setTemperature(@javax.annotation.Nullable BigDecimal temperature) {
    this.temperature = temperature;
  }


  public GetMiscWeather200ResponseHourlyForecastInner weather(@javax.annotation.Nullable String weather) {
    this.weather = weather;
    return this;
  }

  /**
   * 天气状况
   * @return weather
   */
  @javax.annotation.Nullable
  public String getWeather() {
    return weather;
  }

  public void setWeather(@javax.annotation.Nullable String weather) {
    this.weather = weather;
  }


  public GetMiscWeather200ResponseHourlyForecastInner windDirection(@javax.annotation.Nullable String windDirection) {
    this.windDirection = windDirection;
    return this;
  }

  /**
   * 风向（可选）
   * @return windDirection
   */
  @javax.annotation.Nullable
  public String getWindDirection() {
    return windDirection;
  }

  public void setWindDirection(@javax.annotation.Nullable String windDirection) {
    this.windDirection = windDirection;
  }


  public GetMiscWeather200ResponseHourlyForecastInner windSpeed(@javax.annotation.Nullable BigDecimal windSpeed) {
    this.windSpeed = windSpeed;
    return this;
  }

  /**
   * 风速 km/h（可选）
   * @return windSpeed
   */
  @javax.annotation.Nullable
  public BigDecimal getWindSpeed() {
    return windSpeed;
  }

  public void setWindSpeed(@javax.annotation.Nullable BigDecimal windSpeed) {
    this.windSpeed = windSpeed;
  }


  public GetMiscWeather200ResponseHourlyForecastInner windScale(@javax.annotation.Nullable String windScale) {
    this.windScale = windScale;
    return this;
  }

  /**
   * 风力等级（可选）
   * @return windScale
   */
  @javax.annotation.Nullable
  public String getWindScale() {
    return windScale;
  }

  public void setWindScale(@javax.annotation.Nullable String windScale) {
    this.windScale = windScale;
  }


  public GetMiscWeather200ResponseHourlyForecastInner humidity(@javax.annotation.Nullable BigDecimal humidity) {
    this.humidity = humidity;
    return this;
  }

  /**
   * 湿度 %（可选）
   * @return humidity
   */
  @javax.annotation.Nullable
  public BigDecimal getHumidity() {
    return humidity;
  }

  public void setHumidity(@javax.annotation.Nullable BigDecimal humidity) {
    this.humidity = humidity;
  }


  public GetMiscWeather200ResponseHourlyForecastInner precip(@javax.annotation.Nullable BigDecimal precip) {
    this.precip = precip;
    return this;
  }

  /**
   * 降水量 mm（可选）
   * @return precip
   */
  @javax.annotation.Nullable
  public BigDecimal getPrecip() {
    return precip;
  }

  public void setPrecip(@javax.annotation.Nullable BigDecimal precip) {
    this.precip = precip;
  }


  public GetMiscWeather200ResponseHourlyForecastInner feelsLike(@javax.annotation.Nullable BigDecimal feelsLike) {
    this.feelsLike = feelsLike;
    return this;
  }

  /**
   * 体感温度 °C（可选）
   * @return feelsLike
   */
  @javax.annotation.Nullable
  public BigDecimal getFeelsLike() {
    return feelsLike;
  }

  public void setFeelsLike(@javax.annotation.Nullable BigDecimal feelsLike) {
    this.feelsLike = feelsLike;
  }


  public GetMiscWeather200ResponseHourlyForecastInner visibility(@javax.annotation.Nullable BigDecimal visibility) {
    this.visibility = visibility;
    return this;
  }

  /**
   * 能见度 km（可选）
   * @return visibility
   */
  @javax.annotation.Nullable
  public BigDecimal getVisibility() {
    return visibility;
  }

  public void setVisibility(@javax.annotation.Nullable BigDecimal visibility) {
    this.visibility = visibility;
  }


  public GetMiscWeather200ResponseHourlyForecastInner pop(@javax.annotation.Nullable BigDecimal pop) {
    this.pop = pop;
    return this;
  }

  /**
   * 降水概率 %（可选）
   * @return pop
   */
  @javax.annotation.Nullable
  public BigDecimal getPop() {
    return pop;
  }

  public void setPop(@javax.annotation.Nullable BigDecimal pop) {
    this.pop = pop;
  }


  public GetMiscWeather200ResponseHourlyForecastInner uvIndex(@javax.annotation.Nullable BigDecimal uvIndex) {
    this.uvIndex = uvIndex;
    return this;
  }

  /**
   * 紫外线指数（可选，国内城市通常不返回）
   * @return uvIndex
   */
  @javax.annotation.Nullable
  public BigDecimal getUvIndex() {
    return uvIndex;
  }

  public void setUvIndex(@javax.annotation.Nullable BigDecimal uvIndex) {
    this.uvIndex = uvIndex;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMiscWeather200ResponseHourlyForecastInner getMiscWeather200ResponseHourlyForecastInner = (GetMiscWeather200ResponseHourlyForecastInner) o;
    return Objects.equals(this.time, getMiscWeather200ResponseHourlyForecastInner.time) &&
        Objects.equals(this.temperature, getMiscWeather200ResponseHourlyForecastInner.temperature) &&
        Objects.equals(this.weather, getMiscWeather200ResponseHourlyForecastInner.weather) &&
        Objects.equals(this.windDirection, getMiscWeather200ResponseHourlyForecastInner.windDirection) &&
        Objects.equals(this.windSpeed, getMiscWeather200ResponseHourlyForecastInner.windSpeed) &&
        Objects.equals(this.windScale, getMiscWeather200ResponseHourlyForecastInner.windScale) &&
        Objects.equals(this.humidity, getMiscWeather200ResponseHourlyForecastInner.humidity) &&
        Objects.equals(this.precip, getMiscWeather200ResponseHourlyForecastInner.precip) &&
        Objects.equals(this.feelsLike, getMiscWeather200ResponseHourlyForecastInner.feelsLike) &&
        Objects.equals(this.visibility, getMiscWeather200ResponseHourlyForecastInner.visibility) &&
        Objects.equals(this.pop, getMiscWeather200ResponseHourlyForecastInner.pop) &&
        Objects.equals(this.uvIndex, getMiscWeather200ResponseHourlyForecastInner.uvIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(time, temperature, weather, windDirection, windSpeed, windScale, humidity, precip, feelsLike, visibility, pop, uvIndex);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMiscWeather200ResponseHourlyForecastInner {\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    weather: ").append(toIndentedString(weather)).append("\n");
    sb.append("    windDirection: ").append(toIndentedString(windDirection)).append("\n");
    sb.append("    windSpeed: ").append(toIndentedString(windSpeed)).append("\n");
    sb.append("    windScale: ").append(toIndentedString(windScale)).append("\n");
    sb.append("    humidity: ").append(toIndentedString(humidity)).append("\n");
    sb.append("    precip: ").append(toIndentedString(precip)).append("\n");
    sb.append("    feelsLike: ").append(toIndentedString(feelsLike)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    pop: ").append(toIndentedString(pop)).append("\n");
    sb.append("    uvIndex: ").append(toIndentedString(uvIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("time", "temperature", "weather", "wind_direction", "wind_speed", "wind_scale", "humidity", "precip", "feels_like", "visibility", "pop", "uv_index"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetMiscWeather200ResponseHourlyForecastInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetMiscWeather200ResponseHourlyForecastInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetMiscWeather200ResponseHourlyForecastInner is not found in the empty JSON string", GetMiscWeather200ResponseHourlyForecastInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetMiscWeather200ResponseHourlyForecastInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetMiscWeather200ResponseHourlyForecastInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("time") != null && !jsonObj.get("time").isJsonNull()) && !jsonObj.get("time").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `time` to be a primitive type in the JSON string but got `%s`", jsonObj.get("time").toString()));
      }
      if ((jsonObj.get("weather") != null && !jsonObj.get("weather").isJsonNull()) && !jsonObj.get("weather").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `weather` to be a primitive type in the JSON string but got `%s`", jsonObj.get("weather").toString()));
      }
      if ((jsonObj.get("wind_direction") != null && !jsonObj.get("wind_direction").isJsonNull()) && !jsonObj.get("wind_direction").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `wind_direction` to be a primitive type in the JSON string but got `%s`", jsonObj.get("wind_direction").toString()));
      }
      if ((jsonObj.get("wind_scale") != null && !jsonObj.get("wind_scale").isJsonNull()) && !jsonObj.get("wind_scale").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `wind_scale` to be a primitive type in the JSON string but got `%s`", jsonObj.get("wind_scale").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetMiscWeather200ResponseHourlyForecastInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetMiscWeather200ResponseHourlyForecastInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetMiscWeather200ResponseHourlyForecastInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetMiscWeather200ResponseHourlyForecastInner.class));

       return (TypeAdapter<T>) new TypeAdapter<GetMiscWeather200ResponseHourlyForecastInner>() {
           @Override
           public void write(JsonWriter out, GetMiscWeather200ResponseHourlyForecastInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetMiscWeather200ResponseHourlyForecastInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetMiscWeather200ResponseHourlyForecastInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetMiscWeather200ResponseHourlyForecastInner
   * @throws IOException if the JSON string is invalid with respect to GetMiscWeather200ResponseHourlyForecastInner
   */
  public static GetMiscWeather200ResponseHourlyForecastInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetMiscWeather200ResponseHourlyForecastInner.class);
  }

  /**
   * Convert an instance of GetMiscWeather200ResponseHourlyForecastInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

