/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * GetMiscWorldtime200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-11T15:37:17.258797600+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class GetMiscWorldtime200Response {
  public static final String SERIALIZED_NAME_DATETIME = "datetime";
  @SerializedName(SERIALIZED_NAME_DATETIME)
  @javax.annotation.Nullable
  private String datetime;

  public static final String SERIALIZED_NAME_OFFSET_SECONDS = "offset_seconds";
  @SerializedName(SERIALIZED_NAME_OFFSET_SECONDS)
  @javax.annotation.Nullable
  private Integer offsetSeconds;

  public static final String SERIALIZED_NAME_OFFSET_STRING = "offset_string";
  @SerializedName(SERIALIZED_NAME_OFFSET_STRING)
  @javax.annotation.Nullable
  private String offsetString;

  public static final String SERIALIZED_NAME_QUERY = "query";
  @SerializedName(SERIALIZED_NAME_QUERY)
  @javax.annotation.Nullable
  private String query;

  public static final String SERIALIZED_NAME_TIMESTAMP_UNIX = "timestamp_unix";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP_UNIX)
  @javax.annotation.Nullable
  private Integer timestampUnix;

  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  @javax.annotation.Nullable
  private String timezone;

  public static final String SERIALIZED_NAME_WEEKDAY = "weekday";
  @SerializedName(SERIALIZED_NAME_WEEKDAY)
  @javax.annotation.Nullable
  private String weekday;

  public GetMiscWorldtime200Response() {
  }

  public GetMiscWorldtime200Response datetime(@javax.annotation.Nullable String datetime) {
    this.datetime = datetime;
    return this;
  }

  /**
   * Get datetime
   * @return datetime
   */
  @javax.annotation.Nullable
  public String getDatetime() {
    return datetime;
  }

  public void setDatetime(@javax.annotation.Nullable String datetime) {
    this.datetime = datetime;
  }


  public GetMiscWorldtime200Response offsetSeconds(@javax.annotation.Nullable Integer offsetSeconds) {
    this.offsetSeconds = offsetSeconds;
    return this;
  }

  /**
   * Get offsetSeconds
   * @return offsetSeconds
   */
  @javax.annotation.Nullable
  public Integer getOffsetSeconds() {
    return offsetSeconds;
  }

  public void setOffsetSeconds(@javax.annotation.Nullable Integer offsetSeconds) {
    this.offsetSeconds = offsetSeconds;
  }


  public GetMiscWorldtime200Response offsetString(@javax.annotation.Nullable String offsetString) {
    this.offsetString = offsetString;
    return this;
  }

  /**
   * Get offsetString
   * @return offsetString
   */
  @javax.annotation.Nullable
  public String getOffsetString() {
    return offsetString;
  }

  public void setOffsetString(@javax.annotation.Nullable String offsetString) {
    this.offsetString = offsetString;
  }


  public GetMiscWorldtime200Response query(@javax.annotation.Nullable String query) {
    this.query = query;
    return this;
  }

  /**
   * Get query
   * @return query
   */
  @javax.annotation.Nullable
  public String getQuery() {
    return query;
  }

  public void setQuery(@javax.annotation.Nullable String query) {
    this.query = query;
  }


  public GetMiscWorldtime200Response timestampUnix(@javax.annotation.Nullable Integer timestampUnix) {
    this.timestampUnix = timestampUnix;
    return this;
  }

  /**
   * Get timestampUnix
   * @return timestampUnix
   */
  @javax.annotation.Nullable
  public Integer getTimestampUnix() {
    return timestampUnix;
  }

  public void setTimestampUnix(@javax.annotation.Nullable Integer timestampUnix) {
    this.timestampUnix = timestampUnix;
  }


  public GetMiscWorldtime200Response timezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * Get timezone
   * @return timezone
   */
  @javax.annotation.Nullable
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
  }


  public GetMiscWorldtime200Response weekday(@javax.annotation.Nullable String weekday) {
    this.weekday = weekday;
    return this;
  }

  /**
   * Get weekday
   * @return weekday
   */
  @javax.annotation.Nullable
  public String getWeekday() {
    return weekday;
  }

  public void setWeekday(@javax.annotation.Nullable String weekday) {
    this.weekday = weekday;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMiscWorldtime200Response getMiscWorldtime200Response = (GetMiscWorldtime200Response) o;
    return Objects.equals(this.datetime, getMiscWorldtime200Response.datetime) &&
        Objects.equals(this.offsetSeconds, getMiscWorldtime200Response.offsetSeconds) &&
        Objects.equals(this.offsetString, getMiscWorldtime200Response.offsetString) &&
        Objects.equals(this.query, getMiscWorldtime200Response.query) &&
        Objects.equals(this.timestampUnix, getMiscWorldtime200Response.timestampUnix) &&
        Objects.equals(this.timezone, getMiscWorldtime200Response.timezone) &&
        Objects.equals(this.weekday, getMiscWorldtime200Response.weekday);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datetime, offsetSeconds, offsetString, query, timestampUnix, timezone, weekday);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMiscWorldtime200Response {\n");
    sb.append("    datetime: ").append(toIndentedString(datetime)).append("\n");
    sb.append("    offsetSeconds: ").append(toIndentedString(offsetSeconds)).append("\n");
    sb.append("    offsetString: ").append(toIndentedString(offsetString)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    timestampUnix: ").append(toIndentedString(timestampUnix)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    weekday: ").append(toIndentedString(weekday)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("datetime", "offset_seconds", "offset_string", "query", "timestamp_unix", "timezone", "weekday"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetMiscWorldtime200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetMiscWorldtime200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetMiscWorldtime200Response is not found in the empty JSON string", GetMiscWorldtime200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetMiscWorldtime200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetMiscWorldtime200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("datetime") != null && !jsonObj.get("datetime").isJsonNull()) && !jsonObj.get("datetime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `datetime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("datetime").toString()));
      }
      if ((jsonObj.get("offset_string") != null && !jsonObj.get("offset_string").isJsonNull()) && !jsonObj.get("offset_string").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `offset_string` to be a primitive type in the JSON string but got `%s`", jsonObj.get("offset_string").toString()));
      }
      if ((jsonObj.get("query") != null && !jsonObj.get("query").isJsonNull()) && !jsonObj.get("query").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `query` to be a primitive type in the JSON string but got `%s`", jsonObj.get("query").toString()));
      }
      if ((jsonObj.get("timezone") != null && !jsonObj.get("timezone").isJsonNull()) && !jsonObj.get("timezone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `timezone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timezone").toString()));
      }
      if ((jsonObj.get("weekday") != null && !jsonObj.get("weekday").isJsonNull()) && !jsonObj.get("weekday").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `weekday` to be a primitive type in the JSON string but got `%s`", jsonObj.get("weekday").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetMiscWorldtime200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetMiscWorldtime200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetMiscWorldtime200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetMiscWorldtime200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<GetMiscWorldtime200Response>() {
           @Override
           public void write(JsonWriter out, GetMiscWorldtime200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetMiscWorldtime200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetMiscWorldtime200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetMiscWorldtime200Response
   * @throws IOException if the JSON string is invalid with respect to GetMiscWorldtime200Response
   */
  public static GetMiscWorldtime200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetMiscWorldtime200Response.class);
  }

  /**
   * Convert an instance of GetMiscWorldtime200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

