/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.GetNetworkUrlstatus200ResponseOneOf;
import org.openapitools.client.model.GetNetworkUrlstatus200ResponseOneOf1;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Locale;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-26T17:21:00.573689900+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class GetNetworkUrlstatus200Response extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(GetNetworkUrlstatus200Response.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetNetworkUrlstatus200Response.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetNetworkUrlstatus200Response' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetNetworkUrlstatus200ResponseOneOf> adapterGetNetworkUrlstatus200ResponseOneOf = gson.getDelegateAdapter(this, TypeToken.get(GetNetworkUrlstatus200ResponseOneOf.class));
            final TypeAdapter<GetNetworkUrlstatus200ResponseOneOf1> adapterGetNetworkUrlstatus200ResponseOneOf1 = gson.getDelegateAdapter(this, TypeToken.get(GetNetworkUrlstatus200ResponseOneOf1.class));

            return (TypeAdapter<T>) new TypeAdapter<GetNetworkUrlstatus200Response>() {
                @Override
                public void write(JsonWriter out, GetNetworkUrlstatus200Response value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `GetNetworkUrlstatus200ResponseOneOf`
                    if (value.getActualInstance() instanceof GetNetworkUrlstatus200ResponseOneOf) {
                        JsonElement element = adapterGetNetworkUrlstatus200ResponseOneOf.toJsonTree((GetNetworkUrlstatus200ResponseOneOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `GetNetworkUrlstatus200ResponseOneOf1`
                    if (value.getActualInstance() instanceof GetNetworkUrlstatus200ResponseOneOf1) {
                        JsonElement element = adapterGetNetworkUrlstatus200ResponseOneOf1.toJsonTree((GetNetworkUrlstatus200ResponseOneOf1)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: GetNetworkUrlstatus200ResponseOneOf, GetNetworkUrlstatus200ResponseOneOf1");
                }

                @Override
                public GetNetworkUrlstatus200Response read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize GetNetworkUrlstatus200ResponseOneOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        GetNetworkUrlstatus200ResponseOneOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterGetNetworkUrlstatus200ResponseOneOf;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'GetNetworkUrlstatus200ResponseOneOf'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(Locale.ROOT, "Deserialization for GetNetworkUrlstatus200ResponseOneOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'GetNetworkUrlstatus200ResponseOneOf'", e);
                    }
                    // deserialize GetNetworkUrlstatus200ResponseOneOf1
                    try {
                        // validate the JSON object to see if any exception is thrown
                        GetNetworkUrlstatus200ResponseOneOf1.validateJsonElement(jsonElement);
                        actualAdapter = adapterGetNetworkUrlstatus200ResponseOneOf1;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'GetNetworkUrlstatus200ResponseOneOf1'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(Locale.ROOT, "Deserialization for GetNetworkUrlstatus200ResponseOneOf1 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'GetNetworkUrlstatus200ResponseOneOf1'", e);
                    }

                    if (match == 1) {
                        GetNetworkUrlstatus200Response ret = new GetNetworkUrlstatus200Response();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format(Locale.ROOT, "Failed deserialization for GetNetworkUrlstatus200Response: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public GetNetworkUrlstatus200Response() {
        super("oneOf", Boolean.FALSE);
    }

    public GetNetworkUrlstatus200Response(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("GetNetworkUrlstatus200ResponseOneOf", GetNetworkUrlstatus200ResponseOneOf.class);
        schemas.put("GetNetworkUrlstatus200ResponseOneOf1", GetNetworkUrlstatus200ResponseOneOf1.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return GetNetworkUrlstatus200Response.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * GetNetworkUrlstatus200ResponseOneOf, GetNetworkUrlstatus200ResponseOneOf1
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof GetNetworkUrlstatus200ResponseOneOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof GetNetworkUrlstatus200ResponseOneOf1) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be GetNetworkUrlstatus200ResponseOneOf, GetNetworkUrlstatus200ResponseOneOf1");
    }

    /**
     * Get the actual instance, which can be the following:
     * GetNetworkUrlstatus200ResponseOneOf, GetNetworkUrlstatus200ResponseOneOf1
     *
     * @return The actual instance (GetNetworkUrlstatus200ResponseOneOf, GetNetworkUrlstatus200ResponseOneOf1)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `GetNetworkUrlstatus200ResponseOneOf`. If the actual instance is not `GetNetworkUrlstatus200ResponseOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GetNetworkUrlstatus200ResponseOneOf`
     * @throws ClassCastException if the instance is not `GetNetworkUrlstatus200ResponseOneOf`
     */
    public GetNetworkUrlstatus200ResponseOneOf getGetNetworkUrlstatus200ResponseOneOf() throws ClassCastException {
        return (GetNetworkUrlstatus200ResponseOneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `GetNetworkUrlstatus200ResponseOneOf1`. If the actual instance is not `GetNetworkUrlstatus200ResponseOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GetNetworkUrlstatus200ResponseOneOf1`
     * @throws ClassCastException if the instance is not `GetNetworkUrlstatus200ResponseOneOf1`
     */
    public GetNetworkUrlstatus200ResponseOneOf1 getGetNetworkUrlstatus200ResponseOneOf1() throws ClassCastException {
        return (GetNetworkUrlstatus200ResponseOneOf1)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GetNetworkUrlstatus200Response
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with GetNetworkUrlstatus200ResponseOneOf
        try {
            GetNetworkUrlstatus200ResponseOneOf.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(Locale.ROOT, "Deserialization for GetNetworkUrlstatus200ResponseOneOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with GetNetworkUrlstatus200ResponseOneOf1
        try {
            GetNetworkUrlstatus200ResponseOneOf1.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(Locale.ROOT, "Deserialization for GetNetworkUrlstatus200ResponseOneOf1 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format(Locale.ROOT, "The JSON string is invalid for GetNetworkUrlstatus200Response with oneOf schemas: GetNetworkUrlstatus200ResponseOneOf, GetNetworkUrlstatus200ResponseOneOf1. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of GetNetworkUrlstatus200Response given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetNetworkUrlstatus200Response
     * @throws IOException if the JSON string is invalid with respect to GetNetworkUrlstatus200Response
     */
    public static GetNetworkUrlstatus200Response fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GetNetworkUrlstatus200Response.class);
    }

    /**
     * Convert an instance of GetNetworkUrlstatus200Response to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

