/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * 视频UP主信息。
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-11T14:56:09.257300600+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class GetSocialBilibiliVideoinfo200ResponseOwner {
  public static final String SERIALIZED_NAME_MID = "mid";
  @SerializedName(SERIALIZED_NAME_MID)
  @javax.annotation.Nullable
  private BigDecimal mid;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_FACE = "face";
  @SerializedName(SERIALIZED_NAME_FACE)
  @javax.annotation.Nullable
  private String face;

  public GetSocialBilibiliVideoinfo200ResponseOwner() {
  }

  public GetSocialBilibiliVideoinfo200ResponseOwner mid(@javax.annotation.Nullable BigDecimal mid) {
    this.mid = mid;
    return this;
  }

  /**
   * UP主的UID。
   * @return mid
   */
  @javax.annotation.Nullable
  public BigDecimal getMid() {
    return mid;
  }

  public void setMid(@javax.annotation.Nullable BigDecimal mid) {
    this.mid = mid;
  }


  public GetSocialBilibiliVideoinfo200ResponseOwner name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * UP主昵称。
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public GetSocialBilibiliVideoinfo200ResponseOwner face(@javax.annotation.Nullable String face) {
    this.face = face;
    return this;
  }

  /**
   * UP主头像的URL。
   * @return face
   */
  @javax.annotation.Nullable
  public String getFace() {
    return face;
  }

  public void setFace(@javax.annotation.Nullable String face) {
    this.face = face;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSocialBilibiliVideoinfo200ResponseOwner getSocialBilibiliVideoinfo200ResponseOwner = (GetSocialBilibiliVideoinfo200ResponseOwner) o;
    return Objects.equals(this.mid, getSocialBilibiliVideoinfo200ResponseOwner.mid) &&
        Objects.equals(this.name, getSocialBilibiliVideoinfo200ResponseOwner.name) &&
        Objects.equals(this.face, getSocialBilibiliVideoinfo200ResponseOwner.face);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mid, name, face);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSocialBilibiliVideoinfo200ResponseOwner {\n");
    sb.append("    mid: ").append(toIndentedString(mid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    face: ").append(toIndentedString(face)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("mid", "name", "face"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetSocialBilibiliVideoinfo200ResponseOwner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetSocialBilibiliVideoinfo200ResponseOwner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetSocialBilibiliVideoinfo200ResponseOwner is not found in the empty JSON string", GetSocialBilibiliVideoinfo200ResponseOwner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetSocialBilibiliVideoinfo200ResponseOwner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetSocialBilibiliVideoinfo200ResponseOwner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("face") != null && !jsonObj.get("face").isJsonNull()) && !jsonObj.get("face").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `face` to be a primitive type in the JSON string but got `%s`", jsonObj.get("face").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetSocialBilibiliVideoinfo200ResponseOwner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetSocialBilibiliVideoinfo200ResponseOwner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetSocialBilibiliVideoinfo200ResponseOwner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetSocialBilibiliVideoinfo200ResponseOwner.class));

       return (TypeAdapter<T>) new TypeAdapter<GetSocialBilibiliVideoinfo200ResponseOwner>() {
           @Override
           public void write(JsonWriter out, GetSocialBilibiliVideoinfo200ResponseOwner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetSocialBilibiliVideoinfo200ResponseOwner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetSocialBilibiliVideoinfo200ResponseOwner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetSocialBilibiliVideoinfo200ResponseOwner
   * @throws IOException if the JSON string is invalid with respect to GetSocialBilibiliVideoinfo200ResponseOwner
   */
  public static GetSocialBilibiliVideoinfo200ResponseOwner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetSocialBilibiliVideoinfo200ResponseOwner.class);
  }

  /**
   * Convert an instance of GetSocialBilibiliVideoinfo200ResponseOwner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

