/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GetStatusUsage200ResponseAnyOfEndpointsInner;
import org.openapitools.client.model.GetStatusUsage200ResponseAnyOfUnaggregated;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * 查询所有端点时返回的聚合统计数据
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-03T01:17:16.046042800+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class GetStatusUsage200ResponseAnyOf {
  public static final String SERIALIZED_NAME_ENDPOINTS = "endpoints";
  @SerializedName(SERIALIZED_NAME_ENDPOINTS)
  @javax.annotation.Nullable
  private List<GetStatusUsage200ResponseAnyOfEndpointsInner> endpoints = new ArrayList<>();

  public static final String SERIALIZED_NAME_UNAGGREGATED = "unaggregated";
  @SerializedName(SERIALIZED_NAME_UNAGGREGATED)
  @javax.annotation.Nullable
  private GetStatusUsage200ResponseAnyOfUnaggregated unaggregated;

  public GetStatusUsage200ResponseAnyOf() {
  }

  public GetStatusUsage200ResponseAnyOf endpoints(@javax.annotation.Nullable List<GetStatusUsage200ResponseAnyOfEndpointsInner> endpoints) {
    this.endpoints = endpoints;
    return this;
  }

  public GetStatusUsage200ResponseAnyOf addEndpointsItem(GetStatusUsage200ResponseAnyOfEndpointsInner endpointsItem) {
    if (this.endpoints == null) {
      this.endpoints = new ArrayList<>();
    }
    this.endpoints.add(endpointsItem);
    return this;
  }

  /**
   * Get endpoints
   * @return endpoints
   */
  @javax.annotation.Nullable
  public List<GetStatusUsage200ResponseAnyOfEndpointsInner> getEndpoints() {
    return endpoints;
  }

  public void setEndpoints(@javax.annotation.Nullable List<GetStatusUsage200ResponseAnyOfEndpointsInner> endpoints) {
    this.endpoints = endpoints;
  }


  public GetStatusUsage200ResponseAnyOf unaggregated(@javax.annotation.Nullable GetStatusUsage200ResponseAnyOfUnaggregated unaggregated) {
    this.unaggregated = unaggregated;
    return this;
  }

  /**
   * Get unaggregated
   * @return unaggregated
   */
  @javax.annotation.Nullable
  public GetStatusUsage200ResponseAnyOfUnaggregated getUnaggregated() {
    return unaggregated;
  }

  public void setUnaggregated(@javax.annotation.Nullable GetStatusUsage200ResponseAnyOfUnaggregated unaggregated) {
    this.unaggregated = unaggregated;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetStatusUsage200ResponseAnyOf getStatusUsage200ResponseAnyOf = (GetStatusUsage200ResponseAnyOf) o;
    return Objects.equals(this.endpoints, getStatusUsage200ResponseAnyOf.endpoints) &&
        Objects.equals(this.unaggregated, getStatusUsage200ResponseAnyOf.unaggregated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpoints, unaggregated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetStatusUsage200ResponseAnyOf {\n");
    sb.append("    endpoints: ").append(toIndentedString(endpoints)).append("\n");
    sb.append("    unaggregated: ").append(toIndentedString(unaggregated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("endpoints", "unaggregated"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetStatusUsage200ResponseAnyOf
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetStatusUsage200ResponseAnyOf.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetStatusUsage200ResponseAnyOf is not found in the empty JSON string", GetStatusUsage200ResponseAnyOf.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetStatusUsage200ResponseAnyOf.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetStatusUsage200ResponseAnyOf` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("endpoints") != null && !jsonObj.get("endpoints").isJsonNull()) {
        JsonArray jsonArrayendpoints = jsonObj.getAsJsonArray("endpoints");
        if (jsonArrayendpoints != null) {
          // ensure the json data is an array
          if (!jsonObj.get("endpoints").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `endpoints` to be an array in the JSON string but got `%s`", jsonObj.get("endpoints").toString()));
          }

          // validate the optional field `endpoints` (array)
          for (int i = 0; i < jsonArrayendpoints.size(); i++) {
            GetStatusUsage200ResponseAnyOfEndpointsInner.validateJsonElement(jsonArrayendpoints.get(i));
          };
        }
      }
      // validate the optional field `unaggregated`
      if (jsonObj.get("unaggregated") != null && !jsonObj.get("unaggregated").isJsonNull()) {
        GetStatusUsage200ResponseAnyOfUnaggregated.validateJsonElement(jsonObj.get("unaggregated"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetStatusUsage200ResponseAnyOf.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetStatusUsage200ResponseAnyOf' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetStatusUsage200ResponseAnyOf> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetStatusUsage200ResponseAnyOf.class));

       return (TypeAdapter<T>) new TypeAdapter<GetStatusUsage200ResponseAnyOf>() {
           @Override
           public void write(JsonWriter out, GetStatusUsage200ResponseAnyOf value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetStatusUsage200ResponseAnyOf read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetStatusUsage200ResponseAnyOf given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetStatusUsage200ResponseAnyOf
   * @throws IOException if the JSON string is invalid with respect to GetStatusUsage200ResponseAnyOf
   */
  public static GetStatusUsage200ResponseAnyOf fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetStatusUsage200ResponseAnyOf.class);
  }

  /**
   * Convert an instance of GetStatusUsage200ResponseAnyOf to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

