/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GetStatusUsage200ResponseAnyOf;
import org.openapitools.client.model.GetStatusUsage200ResponseAnyOf1;
import org.openapitools.client.model.GetStatusUsage200ResponseAnyOfEndpointsInner;
import org.openapitools.client.model.GetStatusUsage200ResponseAnyOfUnaggregated;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Locale;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-03T01:17:16.046042800+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class GetStatusUsage200Response extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(GetStatusUsage200Response.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetStatusUsage200Response.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetStatusUsage200Response' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetStatusUsage200ResponseAnyOf> adapterGetStatusUsage200ResponseAnyOf = gson.getDelegateAdapter(this, TypeToken.get(GetStatusUsage200ResponseAnyOf.class));
            final TypeAdapter<GetStatusUsage200ResponseAnyOf1> adapterGetStatusUsage200ResponseAnyOf1 = gson.getDelegateAdapter(this, TypeToken.get(GetStatusUsage200ResponseAnyOf1.class));

            return (TypeAdapter<T>) new TypeAdapter<GetStatusUsage200Response>() {
                @Override
                public void write(JsonWriter out, GetStatusUsage200Response value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `GetStatusUsage200ResponseAnyOf`
                    if (value.getActualInstance() instanceof GetStatusUsage200ResponseAnyOf) {
                        JsonElement element = adapterGetStatusUsage200ResponseAnyOf.toJsonTree((GetStatusUsage200ResponseAnyOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `GetStatusUsage200ResponseAnyOf1`
                    if (value.getActualInstance() instanceof GetStatusUsage200ResponseAnyOf1) {
                        JsonElement element = adapterGetStatusUsage200ResponseAnyOf1.toJsonTree((GetStatusUsage200ResponseAnyOf1)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match anyOf schemas: GetStatusUsage200ResponseAnyOf, GetStatusUsage200ResponseAnyOf1");
                }

                @Override
                public GetStatusUsage200Response read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize GetStatusUsage200ResponseAnyOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        GetStatusUsage200ResponseAnyOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterGetStatusUsage200ResponseAnyOf;
                        GetStatusUsage200Response ret = new GetStatusUsage200Response();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(Locale.ROOT, "Deserialization for GetStatusUsage200ResponseAnyOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'GetStatusUsage200ResponseAnyOf'", e);
                    }
                    // deserialize GetStatusUsage200ResponseAnyOf1
                    try {
                        // validate the JSON object to see if any exception is thrown
                        GetStatusUsage200ResponseAnyOf1.validateJsonElement(jsonElement);
                        actualAdapter = adapterGetStatusUsage200ResponseAnyOf1;
                        GetStatusUsage200Response ret = new GetStatusUsage200Response();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(Locale.ROOT, "Deserialization for GetStatusUsage200ResponseAnyOf1 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'GetStatusUsage200ResponseAnyOf1'", e);
                    }

                    throw new IOException(String.format(Locale.ROOT, "Failed deserialization for GetStatusUsage200Response: no class matches result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public GetStatusUsage200Response() {
        super("anyOf", Boolean.FALSE);
    }

    public GetStatusUsage200Response(Object o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("GetStatusUsage200ResponseAnyOf", GetStatusUsage200ResponseAnyOf.class);
        schemas.put("GetStatusUsage200ResponseAnyOf1", GetStatusUsage200ResponseAnyOf1.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return GetStatusUsage200Response.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * GetStatusUsage200ResponseAnyOf, GetStatusUsage200ResponseAnyOf1
     *
     * It could be an instance of the 'anyOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof GetStatusUsage200ResponseAnyOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof GetStatusUsage200ResponseAnyOf1) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be GetStatusUsage200ResponseAnyOf, GetStatusUsage200ResponseAnyOf1");
    }

    /**
     * Get the actual instance, which can be the following:
     * GetStatusUsage200ResponseAnyOf, GetStatusUsage200ResponseAnyOf1
     *
     * @return The actual instance (GetStatusUsage200ResponseAnyOf, GetStatusUsage200ResponseAnyOf1)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `GetStatusUsage200ResponseAnyOf`. If the actual instance is not `GetStatusUsage200ResponseAnyOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GetStatusUsage200ResponseAnyOf`
     * @throws ClassCastException if the instance is not `GetStatusUsage200ResponseAnyOf`
     */
    public GetStatusUsage200ResponseAnyOf getGetStatusUsage200ResponseAnyOf() throws ClassCastException {
        return (GetStatusUsage200ResponseAnyOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `GetStatusUsage200ResponseAnyOf1`. If the actual instance is not `GetStatusUsage200ResponseAnyOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GetStatusUsage200ResponseAnyOf1`
     * @throws ClassCastException if the instance is not `GetStatusUsage200ResponseAnyOf1`
     */
    public GetStatusUsage200ResponseAnyOf1 getGetStatusUsage200ResponseAnyOf1() throws ClassCastException {
        return (GetStatusUsage200ResponseAnyOf1)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GetStatusUsage200Response
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate anyOf schemas one by one
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with GetStatusUsage200ResponseAnyOf
        try {
            GetStatusUsage200ResponseAnyOf.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format(Locale.ROOT, "Deserialization for GetStatusUsage200ResponseAnyOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with GetStatusUsage200ResponseAnyOf1
        try {
            GetStatusUsage200ResponseAnyOf1.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format(Locale.ROOT, "Deserialization for GetStatusUsage200ResponseAnyOf1 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        throw new IOException(String.format(Locale.ROOT, "The JSON string is invalid for GetStatusUsage200Response with anyOf schemas: GetStatusUsage200ResponseAnyOf, GetStatusUsage200ResponseAnyOf1. no class match the result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
    }

    /**
     * Create an instance of GetStatusUsage200Response given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetStatusUsage200Response
     * @throws IOException if the JSON string is invalid with respect to GetStatusUsage200Response
     */
    public static GetStatusUsage200Response fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GetStatusUsage200Response.class);
    }

    /**
     * Convert an instance of GetStatusUsage200Response to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

