/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * 分页信息概览。
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-11T15:37:17.258797600+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class GetSocialBilibiliReplies200ResponsePage {
  public static final String SERIALIZED_NAME_NUM = "num";
  @SerializedName(SERIALIZED_NAME_NUM)
  @javax.annotation.Nullable
  private BigDecimal num;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  @javax.annotation.Nullable
  private BigDecimal size;

  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  @javax.annotation.Nullable
  private BigDecimal count;

  public static final String SERIALIZED_NAME_ACOUNT = "acount";
  @SerializedName(SERIALIZED_NAME_ACOUNT)
  @javax.annotation.Nullable
  private BigDecimal acount;

  public GetSocialBilibiliReplies200ResponsePage() {
  }

  public GetSocialBilibiliReplies200ResponsePage num(@javax.annotation.Nullable BigDecimal num) {
    this.num = num;
    return this;
  }

  /**
   * 当前所在的页码。
   * @return num
   */
  @javax.annotation.Nullable
  public BigDecimal getNum() {
    return num;
  }

  public void setNum(@javax.annotation.Nullable BigDecimal num) {
    this.num = num;
  }


  public GetSocialBilibiliReplies200ResponsePage size(@javax.annotation.Nullable BigDecimal size) {
    this.size = size;
    return this;
  }

  /**
   * 每页的项数。
   * @return size
   */
  @javax.annotation.Nullable
  public BigDecimal getSize() {
    return size;
  }

  public void setSize(@javax.annotation.Nullable BigDecimal size) {
    this.size = size;
  }


  public GetSocialBilibiliReplies200ResponsePage count(@javax.annotation.Nullable BigDecimal count) {
    this.count = count;
    return this;
  }

  /**
   * 根评论（即直接评论视频的评论）的总数。
   * @return count
   */
  @javax.annotation.Nullable
  public BigDecimal getCount() {
    return count;
  }

  public void setCount(@javax.annotation.Nullable BigDecimal count) {
    this.count = count;
  }


  public GetSocialBilibiliReplies200ResponsePage acount(@javax.annotation.Nullable BigDecimal acount) {
    this.acount = acount;
    return this;
  }

  /**
   * 评论区总评论数，包含了所有的楼中楼回复。
   * @return acount
   */
  @javax.annotation.Nullable
  public BigDecimal getAcount() {
    return acount;
  }

  public void setAcount(@javax.annotation.Nullable BigDecimal acount) {
    this.acount = acount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSocialBilibiliReplies200ResponsePage getSocialBilibiliReplies200ResponsePage = (GetSocialBilibiliReplies200ResponsePage) o;
    return Objects.equals(this.num, getSocialBilibiliReplies200ResponsePage.num) &&
        Objects.equals(this.size, getSocialBilibiliReplies200ResponsePage.size) &&
        Objects.equals(this.count, getSocialBilibiliReplies200ResponsePage.count) &&
        Objects.equals(this.acount, getSocialBilibiliReplies200ResponsePage.acount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(num, size, count, acount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSocialBilibiliReplies200ResponsePage {\n");
    sb.append("    num: ").append(toIndentedString(num)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    acount: ").append(toIndentedString(acount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("num", "size", "count", "acount"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetSocialBilibiliReplies200ResponsePage
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetSocialBilibiliReplies200ResponsePage.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetSocialBilibiliReplies200ResponsePage is not found in the empty JSON string", GetSocialBilibiliReplies200ResponsePage.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetSocialBilibiliReplies200ResponsePage.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetSocialBilibiliReplies200ResponsePage` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetSocialBilibiliReplies200ResponsePage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetSocialBilibiliReplies200ResponsePage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetSocialBilibiliReplies200ResponsePage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetSocialBilibiliReplies200ResponsePage.class));

       return (TypeAdapter<T>) new TypeAdapter<GetSocialBilibiliReplies200ResponsePage>() {
           @Override
           public void write(JsonWriter out, GetSocialBilibiliReplies200ResponsePage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetSocialBilibiliReplies200ResponsePage read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetSocialBilibiliReplies200ResponsePage given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetSocialBilibiliReplies200ResponsePage
   * @throws IOException if the JSON string is invalid with respect to GetSocialBilibiliReplies200ResponsePage
   */
  public static GetSocialBilibiliReplies200ResponsePage fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetSocialBilibiliReplies200ResponsePage.class);
  }

  /**
   * Convert an instance of GetSocialBilibiliReplies200ResponsePage to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

