/*
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.GetSocialBilibiliLiveroom200ResponseNewPendantsBadge;
import org.openapitools.client.model.GetSocialBilibiliLiveroom200ResponseNewPendantsFrame;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * 主播佩戴信息。
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-15T11:28:35.443476300+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class GetSocialBilibiliLiveroom200ResponseNewPendants {
  public static final String SERIALIZED_NAME_FRAME = "frame";
  @SerializedName(SERIALIZED_NAME_FRAME)
  @javax.annotation.Nullable
  private GetSocialBilibiliLiveroom200ResponseNewPendantsFrame frame;

  public static final String SERIALIZED_NAME_BADGE = "badge";
  @SerializedName(SERIALIZED_NAME_BADGE)
  @javax.annotation.Nullable
  private GetSocialBilibiliLiveroom200ResponseNewPendantsBadge badge;

  public GetSocialBilibiliLiveroom200ResponseNewPendants() {
  }

  public GetSocialBilibiliLiveroom200ResponseNewPendants frame(@javax.annotation.Nullable GetSocialBilibiliLiveroom200ResponseNewPendantsFrame frame) {
    this.frame = frame;
    return this;
  }

  /**
   * Get frame
   * @return frame
   */
  @javax.annotation.Nullable
  public GetSocialBilibiliLiveroom200ResponseNewPendantsFrame getFrame() {
    return frame;
  }

  public void setFrame(@javax.annotation.Nullable GetSocialBilibiliLiveroom200ResponseNewPendantsFrame frame) {
    this.frame = frame;
  }


  public GetSocialBilibiliLiveroom200ResponseNewPendants badge(@javax.annotation.Nullable GetSocialBilibiliLiveroom200ResponseNewPendantsBadge badge) {
    this.badge = badge;
    return this;
  }

  /**
   * Get badge
   * @return badge
   */
  @javax.annotation.Nullable
  public GetSocialBilibiliLiveroom200ResponseNewPendantsBadge getBadge() {
    return badge;
  }

  public void setBadge(@javax.annotation.Nullable GetSocialBilibiliLiveroom200ResponseNewPendantsBadge badge) {
    this.badge = badge;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSocialBilibiliLiveroom200ResponseNewPendants getSocialBilibiliLiveroom200ResponseNewPendants = (GetSocialBilibiliLiveroom200ResponseNewPendants) o;
    return Objects.equals(this.frame, getSocialBilibiliLiveroom200ResponseNewPendants.frame) &&
        Objects.equals(this.badge, getSocialBilibiliLiveroom200ResponseNewPendants.badge);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(frame, badge);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSocialBilibiliLiveroom200ResponseNewPendants {\n");
    sb.append("    frame: ").append(toIndentedString(frame)).append("\n");
    sb.append("    badge: ").append(toIndentedString(badge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("frame", "badge"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetSocialBilibiliLiveroom200ResponseNewPendants
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetSocialBilibiliLiveroom200ResponseNewPendants.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetSocialBilibiliLiveroom200ResponseNewPendants is not found in the empty JSON string", GetSocialBilibiliLiveroom200ResponseNewPendants.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetSocialBilibiliLiveroom200ResponseNewPendants.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetSocialBilibiliLiveroom200ResponseNewPendants` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `frame`
      if (jsonObj.get("frame") != null && !jsonObj.get("frame").isJsonNull()) {
        GetSocialBilibiliLiveroom200ResponseNewPendantsFrame.validateJsonElement(jsonObj.get("frame"));
      }
      // validate the optional field `badge`
      if (jsonObj.get("badge") != null && !jsonObj.get("badge").isJsonNull()) {
        GetSocialBilibiliLiveroom200ResponseNewPendantsBadge.validateJsonElement(jsonObj.get("badge"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetSocialBilibiliLiveroom200ResponseNewPendants.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetSocialBilibiliLiveroom200ResponseNewPendants' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetSocialBilibiliLiveroom200ResponseNewPendants> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetSocialBilibiliLiveroom200ResponseNewPendants.class));

       return (TypeAdapter<T>) new TypeAdapter<GetSocialBilibiliLiveroom200ResponseNewPendants>() {
           @Override
           public void write(JsonWriter out, GetSocialBilibiliLiveroom200ResponseNewPendants value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetSocialBilibiliLiveroom200ResponseNewPendants read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetSocialBilibiliLiveroom200ResponseNewPendants given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetSocialBilibiliLiveroom200ResponseNewPendants
   * @throws IOException if the JSON string is invalid with respect to GetSocialBilibiliLiveroom200ResponseNewPendants
   */
  public static GetSocialBilibiliLiveroom200ResponseNewPendants fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetSocialBilibiliLiveroom200ResponseNewPendants.class);
  }

  /**
   * Convert an instance of GetSocialBilibiliLiveroom200ResponseNewPendants to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

