/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.GetSocialBilibiliReplies200ResponseRepliesInnerMemberLevelInfo;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * 发表评论的用户信息。
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-11T14:56:09.257300600+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class GetSocialBilibiliReplies200ResponseRepliesInnerMember {
  public static final String SERIALIZED_NAME_UNAME = "uname";
  @SerializedName(SERIALIZED_NAME_UNAME)
  @javax.annotation.Nullable
  private String uname;

  public static final String SERIALIZED_NAME_SEX = "sex";
  @SerializedName(SERIALIZED_NAME_SEX)
  @javax.annotation.Nullable
  private String sex;

  public static final String SERIALIZED_NAME_AVATAR = "avatar";
  @SerializedName(SERIALIZED_NAME_AVATAR)
  @javax.annotation.Nullable
  private String avatar;

  public static final String SERIALIZED_NAME_LEVEL_INFO = "level_info";
  @SerializedName(SERIALIZED_NAME_LEVEL_INFO)
  @javax.annotation.Nullable
  private GetSocialBilibiliReplies200ResponseRepliesInnerMemberLevelInfo levelInfo;

  public GetSocialBilibiliReplies200ResponseRepliesInnerMember() {
  }

  public GetSocialBilibiliReplies200ResponseRepliesInnerMember uname(@javax.annotation.Nullable String uname) {
    this.uname = uname;
    return this;
  }

  /**
   * 用户昵称。
   * @return uname
   */
  @javax.annotation.Nullable
  public String getUname() {
    return uname;
  }

  public void setUname(@javax.annotation.Nullable String uname) {
    this.uname = uname;
  }


  public GetSocialBilibiliReplies200ResponseRepliesInnerMember sex(@javax.annotation.Nullable String sex) {
    this.sex = sex;
    return this;
  }

  /**
   * 用户性别。
   * @return sex
   */
  @javax.annotation.Nullable
  public String getSex() {
    return sex;
  }

  public void setSex(@javax.annotation.Nullable String sex) {
    this.sex = sex;
  }


  public GetSocialBilibiliReplies200ResponseRepliesInnerMember avatar(@javax.annotation.Nullable String avatar) {
    this.avatar = avatar;
    return this;
  }

  /**
   * 用户头像的URL。
   * @return avatar
   */
  @javax.annotation.Nullable
  public String getAvatar() {
    return avatar;
  }

  public void setAvatar(@javax.annotation.Nullable String avatar) {
    this.avatar = avatar;
  }


  public GetSocialBilibiliReplies200ResponseRepliesInnerMember levelInfo(@javax.annotation.Nullable GetSocialBilibiliReplies200ResponseRepliesInnerMemberLevelInfo levelInfo) {
    this.levelInfo = levelInfo;
    return this;
  }

  /**
   * Get levelInfo
   * @return levelInfo
   */
  @javax.annotation.Nullable
  public GetSocialBilibiliReplies200ResponseRepliesInnerMemberLevelInfo getLevelInfo() {
    return levelInfo;
  }

  public void setLevelInfo(@javax.annotation.Nullable GetSocialBilibiliReplies200ResponseRepliesInnerMemberLevelInfo levelInfo) {
    this.levelInfo = levelInfo;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSocialBilibiliReplies200ResponseRepliesInnerMember getSocialBilibiliReplies200ResponseRepliesInnerMember = (GetSocialBilibiliReplies200ResponseRepliesInnerMember) o;
    return Objects.equals(this.uname, getSocialBilibiliReplies200ResponseRepliesInnerMember.uname) &&
        Objects.equals(this.sex, getSocialBilibiliReplies200ResponseRepliesInnerMember.sex) &&
        Objects.equals(this.avatar, getSocialBilibiliReplies200ResponseRepliesInnerMember.avatar) &&
        Objects.equals(this.levelInfo, getSocialBilibiliReplies200ResponseRepliesInnerMember.levelInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uname, sex, avatar, levelInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSocialBilibiliReplies200ResponseRepliesInnerMember {\n");
    sb.append("    uname: ").append(toIndentedString(uname)).append("\n");
    sb.append("    sex: ").append(toIndentedString(sex)).append("\n");
    sb.append("    avatar: ").append(toIndentedString(avatar)).append("\n");
    sb.append("    levelInfo: ").append(toIndentedString(levelInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("uname", "sex", "avatar", "level_info"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetSocialBilibiliReplies200ResponseRepliesInnerMember
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetSocialBilibiliReplies200ResponseRepliesInnerMember.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetSocialBilibiliReplies200ResponseRepliesInnerMember is not found in the empty JSON string", GetSocialBilibiliReplies200ResponseRepliesInnerMember.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetSocialBilibiliReplies200ResponseRepliesInnerMember.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetSocialBilibiliReplies200ResponseRepliesInnerMember` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("uname") != null && !jsonObj.get("uname").isJsonNull()) && !jsonObj.get("uname").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `uname` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uname").toString()));
      }
      if ((jsonObj.get("sex") != null && !jsonObj.get("sex").isJsonNull()) && !jsonObj.get("sex").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `sex` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sex").toString()));
      }
      if ((jsonObj.get("avatar") != null && !jsonObj.get("avatar").isJsonNull()) && !jsonObj.get("avatar").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `avatar` to be a primitive type in the JSON string but got `%s`", jsonObj.get("avatar").toString()));
      }
      // validate the optional field `level_info`
      if (jsonObj.get("level_info") != null && !jsonObj.get("level_info").isJsonNull()) {
        GetSocialBilibiliReplies200ResponseRepliesInnerMemberLevelInfo.validateJsonElement(jsonObj.get("level_info"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetSocialBilibiliReplies200ResponseRepliesInnerMember.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetSocialBilibiliReplies200ResponseRepliesInnerMember' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetSocialBilibiliReplies200ResponseRepliesInnerMember> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetSocialBilibiliReplies200ResponseRepliesInnerMember.class));

       return (TypeAdapter<T>) new TypeAdapter<GetSocialBilibiliReplies200ResponseRepliesInnerMember>() {
           @Override
           public void write(JsonWriter out, GetSocialBilibiliReplies200ResponseRepliesInnerMember value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetSocialBilibiliReplies200ResponseRepliesInnerMember read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetSocialBilibiliReplies200ResponseRepliesInnerMember given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetSocialBilibiliReplies200ResponseRepliesInnerMember
   * @throws IOException if the JSON string is invalid with respect to GetSocialBilibiliReplies200ResponseRepliesInnerMember
   */
  public static GetSocialBilibiliReplies200ResponseRepliesInnerMember fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetSocialBilibiliReplies200ResponseRepliesInnerMember.class);
  }

  /**
   * Convert an instance of GetSocialBilibiliReplies200ResponseRepliesInnerMember to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

