/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-11T14:56:09.257300600+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result {
  public static final String SERIALIZED_NAME_MARKDOWN = "markdown";
  @SerializedName(SERIALIZED_NAME_MARKDOWN)
  @javax.annotation.Nullable
  private String markdown;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  @javax.annotation.Nullable
  private Integer size;

  public GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result() {
  }

  public GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result markdown(@javax.annotation.Nullable String markdown) {
    this.markdown = markdown;
    return this;
  }

  /**
   * Get markdown
   * @return markdown
   */
  @javax.annotation.Nullable
  public String getMarkdown() {
    return markdown;
  }

  public void setMarkdown(@javax.annotation.Nullable String markdown) {
    this.markdown = markdown;
  }


  public GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result size(@javax.annotation.Nullable Integer size) {
    this.size = size;
    return this;
  }

  /**
   * Get size
   * @return size
   */
  @javax.annotation.Nullable
  public Integer getSize() {
    return size;
  }

  public void setSize(@javax.annotation.Nullable Integer size) {
    this.size = size;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result getWebTomarkdownAsyncStatus200ResponseAnyOf2Result = (GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result) o;
    return Objects.equals(this.markdown, getWebTomarkdownAsyncStatus200ResponseAnyOf2Result.markdown) &&
        Objects.equals(this.size, getWebTomarkdownAsyncStatus200ResponseAnyOf2Result.size);
  }

  @Override
  public int hashCode() {
    return Objects.hash(markdown, size);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result {\n");
    sb.append("    markdown: ").append(toIndentedString(markdown)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("markdown", "size"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result is not found in the empty JSON string", GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("markdown") != null && !jsonObj.get("markdown").isJsonNull()) && !jsonObj.get("markdown").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `markdown` to be a primitive type in the JSON string but got `%s`", jsonObj.get("markdown").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result.class));

       return (TypeAdapter<T>) new TypeAdapter<GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result>() {
           @Override
           public void write(JsonWriter out, GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result
   * @throws IOException if the JSON string is invalid with respect to GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result
   */
  public static GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result.class);
  }

  /**
   * Convert an instance of GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

