/*
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PostImageOcr200ResponseWordsResultInnerLocation;
import org.openapitools.client.model.PostImageOcr200ResponseWordsResultInnerVertexesLocationInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * PostImageOcr200ResponseWordsResultInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-15T11:28:35.443476300+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class PostImageOcr200ResponseWordsResultInner {
  public static final String SERIALIZED_NAME_WORDS = "words";
  @SerializedName(SERIALIZED_NAME_WORDS)
  @javax.annotation.Nullable
  private String words;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  @javax.annotation.Nullable
  private PostImageOcr200ResponseWordsResultInnerLocation location;

  public static final String SERIALIZED_NAME_VERTEXES_LOCATION = "vertexes_location";
  @SerializedName(SERIALIZED_NAME_VERTEXES_LOCATION)
  @javax.annotation.Nullable
  private List<PostImageOcr200ResponseWordsResultInnerVertexesLocationInner> vertexesLocation = new ArrayList<>();

  public static final String SERIALIZED_NAME_SCORE = "score";
  @SerializedName(SERIALIZED_NAME_SCORE)
  @javax.annotation.Nullable
  private BigDecimal score;

  public PostImageOcr200ResponseWordsResultInner() {
  }

  public PostImageOcr200ResponseWordsResultInner words(@javax.annotation.Nullable String words) {
    this.words = words;
    return this;
  }

  /**
   * 当前文字片段的识别结果。
   * @return words
   */
  @javax.annotation.Nullable
  public String getWords() {
    return words;
  }

  public void setWords(@javax.annotation.Nullable String words) {
    this.words = words;
  }


  public PostImageOcr200ResponseWordsResultInner location(@javax.annotation.Nullable PostImageOcr200ResponseWordsResultInnerLocation location) {
    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @javax.annotation.Nullable
  public PostImageOcr200ResponseWordsResultInnerLocation getLocation() {
    return location;
  }

  public void setLocation(@javax.annotation.Nullable PostImageOcr200ResponseWordsResultInnerLocation location) {
    this.location = location;
  }


  public PostImageOcr200ResponseWordsResultInner vertexesLocation(@javax.annotation.Nullable List<PostImageOcr200ResponseWordsResultInnerVertexesLocationInner> vertexesLocation) {
    this.vertexesLocation = vertexesLocation;
    return this;
  }

  public PostImageOcr200ResponseWordsResultInner addVertexesLocationItem(PostImageOcr200ResponseWordsResultInnerVertexesLocationInner vertexesLocationItem) {
    if (this.vertexesLocation == null) {
      this.vertexesLocation = new ArrayList<>();
    }
    this.vertexesLocation.add(vertexesLocationItem);
    return this;
  }

  /**
   * 当前文字片段的顶点坐标列表。只有在 &#x60;need_location&#x3D;true&#x60; 时才会返回。
   * @return vertexesLocation
   */
  @javax.annotation.Nullable
  public List<PostImageOcr200ResponseWordsResultInnerVertexesLocationInner> getVertexesLocation() {
    return vertexesLocation;
  }

  public void setVertexesLocation(@javax.annotation.Nullable List<PostImageOcr200ResponseWordsResultInnerVertexesLocationInner> vertexesLocation) {
    this.vertexesLocation = vertexesLocation;
  }


  public PostImageOcr200ResponseWordsResultInner score(@javax.annotation.Nullable BigDecimal score) {
    this.score = score;
    return this;
  }

  /**
   * 当前文字片段的置信度。部分结果会返回。
   * @return score
   */
  @javax.annotation.Nullable
  public BigDecimal getScore() {
    return score;
  }

  public void setScore(@javax.annotation.Nullable BigDecimal score) {
    this.score = score;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostImageOcr200ResponseWordsResultInner postImageOcr200ResponseWordsResultInner = (PostImageOcr200ResponseWordsResultInner) o;
    return Objects.equals(this.words, postImageOcr200ResponseWordsResultInner.words) &&
        Objects.equals(this.location, postImageOcr200ResponseWordsResultInner.location) &&
        Objects.equals(this.vertexesLocation, postImageOcr200ResponseWordsResultInner.vertexesLocation) &&
        Objects.equals(this.score, postImageOcr200ResponseWordsResultInner.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(words, location, vertexesLocation, score);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostImageOcr200ResponseWordsResultInner {\n");
    sb.append("    words: ").append(toIndentedString(words)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    vertexesLocation: ").append(toIndentedString(vertexesLocation)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("words", "location", "vertexes_location", "score"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PostImageOcr200ResponseWordsResultInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PostImageOcr200ResponseWordsResultInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in PostImageOcr200ResponseWordsResultInner is not found in the empty JSON string", PostImageOcr200ResponseWordsResultInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PostImageOcr200ResponseWordsResultInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PostImageOcr200ResponseWordsResultInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("words") != null && !jsonObj.get("words").isJsonNull()) && !jsonObj.get("words").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `words` to be a primitive type in the JSON string but got `%s`", jsonObj.get("words").toString()));
      }
      // validate the optional field `location`
      if (jsonObj.get("location") != null && !jsonObj.get("location").isJsonNull()) {
        PostImageOcr200ResponseWordsResultInnerLocation.validateJsonElement(jsonObj.get("location"));
      }
      if (jsonObj.get("vertexes_location") != null && !jsonObj.get("vertexes_location").isJsonNull()) {
        JsonArray jsonArrayvertexesLocation = jsonObj.getAsJsonArray("vertexes_location");
        if (jsonArrayvertexesLocation != null) {
          // ensure the json data is an array
          if (!jsonObj.get("vertexes_location").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `vertexes_location` to be an array in the JSON string but got `%s`", jsonObj.get("vertexes_location").toString()));
          }

          // validate the optional field `vertexes_location` (array)
          for (int i = 0; i < jsonArrayvertexesLocation.size(); i++) {
            PostImageOcr200ResponseWordsResultInnerVertexesLocationInner.validateJsonElement(jsonArrayvertexesLocation.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostImageOcr200ResponseWordsResultInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostImageOcr200ResponseWordsResultInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostImageOcr200ResponseWordsResultInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostImageOcr200ResponseWordsResultInner.class));

       return (TypeAdapter<T>) new TypeAdapter<PostImageOcr200ResponseWordsResultInner>() {
           @Override
           public void write(JsonWriter out, PostImageOcr200ResponseWordsResultInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostImageOcr200ResponseWordsResultInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PostImageOcr200ResponseWordsResultInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PostImageOcr200ResponseWordsResultInner
   * @throws IOException if the JSON string is invalid with respect to PostImageOcr200ResponseWordsResultInner
   */
  public static PostImageOcr200ResponseWordsResultInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostImageOcr200ResponseWordsResultInner.class);
  }

  /**
   * Convert an instance of PostImageOcr200ResponseWordsResultInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

