/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * PostSearchAggregate200ResponseSourcesInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-18T19:07:22.504751100+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class PostSearchAggregate200ResponseSourcesInner {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_RESULT_COUNT = "result_count";
  @SerializedName(SERIALIZED_NAME_RESULT_COUNT)
  @javax.annotation.Nullable
  private Integer resultCount;

  public static final String SERIALIZED_NAME_ELAPSED_MS = "elapsed_ms";
  @SerializedName(SERIALIZED_NAME_ELAPSED_MS)
  @javax.annotation.Nullable
  private Integer elapsedMs;

  public static final String SERIALIZED_NAME_FIRST_RESULT_HOST = "first_result_host";
  @SerializedName(SERIALIZED_NAME_FIRST_RESULT_HOST)
  @javax.annotation.Nullable
  private String firstResultHost;

  public PostSearchAggregate200ResponseSourcesInner() {
  }

  public PostSearchAggregate200ResponseSourcesInner name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public PostSearchAggregate200ResponseSourcesInner status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public PostSearchAggregate200ResponseSourcesInner resultCount(@javax.annotation.Nullable Integer resultCount) {
    this.resultCount = resultCount;
    return this;
  }

  /**
   * Get resultCount
   * @return resultCount
   */
  @javax.annotation.Nullable
  public Integer getResultCount() {
    return resultCount;
  }

  public void setResultCount(@javax.annotation.Nullable Integer resultCount) {
    this.resultCount = resultCount;
  }


  public PostSearchAggregate200ResponseSourcesInner elapsedMs(@javax.annotation.Nullable Integer elapsedMs) {
    this.elapsedMs = elapsedMs;
    return this;
  }

  /**
   * Get elapsedMs
   * @return elapsedMs
   */
  @javax.annotation.Nullable
  public Integer getElapsedMs() {
    return elapsedMs;
  }

  public void setElapsedMs(@javax.annotation.Nullable Integer elapsedMs) {
    this.elapsedMs = elapsedMs;
  }


  public PostSearchAggregate200ResponseSourcesInner firstResultHost(@javax.annotation.Nullable String firstResultHost) {
    this.firstResultHost = firstResultHost;
    return this;
  }

  /**
   * Get firstResultHost
   * @return firstResultHost
   */
  @javax.annotation.Nullable
  public String getFirstResultHost() {
    return firstResultHost;
  }

  public void setFirstResultHost(@javax.annotation.Nullable String firstResultHost) {
    this.firstResultHost = firstResultHost;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostSearchAggregate200ResponseSourcesInner postSearchAggregate200ResponseSourcesInner = (PostSearchAggregate200ResponseSourcesInner) o;
    return Objects.equals(this.name, postSearchAggregate200ResponseSourcesInner.name) &&
        Objects.equals(this.status, postSearchAggregate200ResponseSourcesInner.status) &&
        Objects.equals(this.resultCount, postSearchAggregate200ResponseSourcesInner.resultCount) &&
        Objects.equals(this.elapsedMs, postSearchAggregate200ResponseSourcesInner.elapsedMs) &&
        Objects.equals(this.firstResultHost, postSearchAggregate200ResponseSourcesInner.firstResultHost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, status, resultCount, elapsedMs, firstResultHost);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostSearchAggregate200ResponseSourcesInner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    resultCount: ").append(toIndentedString(resultCount)).append("\n");
    sb.append("    elapsedMs: ").append(toIndentedString(elapsedMs)).append("\n");
    sb.append("    firstResultHost: ").append(toIndentedString(firstResultHost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "status", "result_count", "elapsed_ms", "first_result_host"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PostSearchAggregate200ResponseSourcesInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PostSearchAggregate200ResponseSourcesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in PostSearchAggregate200ResponseSourcesInner is not found in the empty JSON string", PostSearchAggregate200ResponseSourcesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PostSearchAggregate200ResponseSourcesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PostSearchAggregate200ResponseSourcesInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("first_result_host") != null && !jsonObj.get("first_result_host").isJsonNull()) && !jsonObj.get("first_result_host").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `first_result_host` to be a primitive type in the JSON string but got `%s`", jsonObj.get("first_result_host").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostSearchAggregate200ResponseSourcesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostSearchAggregate200ResponseSourcesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostSearchAggregate200ResponseSourcesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostSearchAggregate200ResponseSourcesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<PostSearchAggregate200ResponseSourcesInner>() {
           @Override
           public void write(JsonWriter out, PostSearchAggregate200ResponseSourcesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostSearchAggregate200ResponseSourcesInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PostSearchAggregate200ResponseSourcesInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PostSearchAggregate200ResponseSourcesInner
   * @throws IOException if the JSON string is invalid with respect to PostSearchAggregate200ResponseSourcesInner
   */
  public static PostSearchAggregate200ResponseSourcesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostSearchAggregate200ResponseSourcesInner.class);
  }

  /**
   * Convert an instance of PostSearchAggregate200ResponseSourcesInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

