/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * PostClipzyStoreRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-18T19:07:22.504751100+08:00[Asia/Shanghai]", comments = "Generator version: 7.17.0")
public class PostClipzyStoreRequest {
  public static final String SERIALIZED_NAME_COMPRESSED_DATA = "compressedData";
  @SerializedName(SERIALIZED_NAME_COMPRESSED_DATA)
  @javax.annotation.Nonnull
  private String compressedData;

  public static final String SERIALIZED_NAME_TTL = "ttl";
  @SerializedName(SERIALIZED_NAME_TTL)
  @javax.annotation.Nullable
  private BigDecimal ttl;

  public PostClipzyStoreRequest() {
  }

  public PostClipzyStoreRequest compressedData(@javax.annotation.Nonnull String compressedData) {
    this.compressedData = compressedData;
    return this;
  }

  /**
   * 必需：经过加密和 LZString 压缩后的 Base64 字符串。请参考文档首页的JS代码示例。
   * @return compressedData
   */
  @javax.annotation.Nonnull
  public String getCompressedData() {
    return compressedData;
  }

  public void setCompressedData(@javax.annotation.Nonnull String compressedData) {
    this.compressedData = compressedData;
  }


  public PostClipzyStoreRequest ttl(@javax.annotation.Nullable BigDecimal ttl) {
    this.ttl = ttl;
    return this;
  }

  /**
   * 可选：片段的留存时间（秒）。正数表示秒数（最大约30天），-1 表示永久存储。默认为 3600。
   * @return ttl
   */
  @javax.annotation.Nullable
  public BigDecimal getTtl() {
    return ttl;
  }

  public void setTtl(@javax.annotation.Nullable BigDecimal ttl) {
    this.ttl = ttl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostClipzyStoreRequest postClipzyStoreRequest = (PostClipzyStoreRequest) o;
    return Objects.equals(this.compressedData, postClipzyStoreRequest.compressedData) &&
        Objects.equals(this.ttl, postClipzyStoreRequest.ttl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(compressedData, ttl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostClipzyStoreRequest {\n");
    sb.append("    compressedData: ").append(toIndentedString(compressedData)).append("\n");
    sb.append("    ttl: ").append(toIndentedString(ttl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("compressedData", "ttl"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("compressedData"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PostClipzyStoreRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PostClipzyStoreRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in PostClipzyStoreRequest is not found in the empty JSON string", PostClipzyStoreRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PostClipzyStoreRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PostClipzyStoreRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PostClipzyStoreRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("compressedData").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `compressedData` to be a primitive type in the JSON string but got `%s`", jsonObj.get("compressedData").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostClipzyStoreRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostClipzyStoreRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostClipzyStoreRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostClipzyStoreRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<PostClipzyStoreRequest>() {
           @Override
           public void write(JsonWriter out, PostClipzyStoreRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostClipzyStoreRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PostClipzyStoreRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PostClipzyStoreRequest
   * @throws IOException if the JSON string is invalid with respect to PostClipzyStoreRequest
   */
  public static PostClipzyStoreRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostClipzyStoreRequest.class);
  }

  /**
   * Convert an instance of PostClipzyStoreRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

