/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.GetConvertUnixtime200Response;
import org.openapitools.client.model.GetConvertUnixtime400Response;
import org.openapitools.client.model.PostConvertJson200Response;
import org.openapitools.client.model.PostConvertJson400Response;
import org.openapitools.client.model.PostConvertJsonRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ConvertApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ConvertApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ConvertApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getConvertUnixtime
     * @param time 一个智能时间参数，可传入Unix时间戳（10位或13位）或标准日期字符串（如 &#39;2023-10-27 10:30:00&#39;），系统将自动识别并转换。 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 转换成功！响应中会同时包含标准日期字符串和秒级Unix时间戳，方便你使用。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 请求失败。请检查你提供的 &#x60;time&#x60; 参数是否是有效的时间戳或我们支持的日期格式（YYYY-MM-DD HH:mm:ss）。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getConvertUnixtimeCall(@javax.annotation.Nonnull String time, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/convert/unixtime";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (time != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("time", time));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getConvertUnixtimeValidateBeforeCall(@javax.annotation.Nonnull String time, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'time' is set
        if (time == null) {
            throw new ApiException("Missing the required parameter 'time' when calling getConvertUnixtime(Async)");
        }

        return getConvertUnixtimeCall(time, _callback);

    }

    /**
     * Unix时间戳与日期字符串双向转换
     * 时间戳和日期字符串，哪个用着更顺手？别纠结了，这个接口让你轻松拥有两种格式！  ## 功能概述 这是一个非常智能的转换器。你给它一个 Unix 时间戳，它还你一个人类可读的日期时间；你给它一个日期时间字符串，它还你一个 Unix 时间戳。它会自动识别你输入的是哪种格式。  ## 使用须知 这个接口非常智能，能够自动识别输入格式：  - **输入时间戳**：支持10位秒级（如 &#x60;1672531200&#x60;）和13位毫秒级（如 &#x60;1672531200000&#x60;）。 - **输入日期字符串**：为了确保准确性，推荐使用 &#x60;YYYY-MM-DD HH:mm:ss&#x60; 标准格式（如 &#x60;2023-01-01 08:00:00&#x60;）。  &gt; [!TIP] &gt; 无论你输入哪种格式，响应中都会同时包含标准日期字符串和秒级Unix时间戳，方便你按需取用。  ## 错误处理指南 - **400 Bad Request**: 如果你提供的 &#x60;time&#x60; 参数既不是有效的时间戳，也不是我们支持的日期格式，就会收到这个错误。请检查你的输入值。
     * @param time 一个智能时间参数，可传入Unix时间戳（10位或13位）或标准日期字符串（如 &#39;2023-10-27 10:30:00&#39;），系统将自动识别并转换。 (required)
     * @return GetConvertUnixtime200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 转换成功！响应中会同时包含标准日期字符串和秒级Unix时间戳，方便你使用。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 请求失败。请检查你提供的 &#x60;time&#x60; 参数是否是有效的时间戳或我们支持的日期格式（YYYY-MM-DD HH:mm:ss）。 </td><td>  -  </td></tr>
     </table>
     */
    public GetConvertUnixtime200Response getConvertUnixtime(@javax.annotation.Nonnull String time) throws ApiException {
        ApiResponse<GetConvertUnixtime200Response> localVarResp = getConvertUnixtimeWithHttpInfo(time);
        return localVarResp.getData();
    }

    /**
     * Unix时间戳与日期字符串双向转换
     * 时间戳和日期字符串，哪个用着更顺手？别纠结了，这个接口让你轻松拥有两种格式！  ## 功能概述 这是一个非常智能的转换器。你给它一个 Unix 时间戳，它还你一个人类可读的日期时间；你给它一个日期时间字符串，它还你一个 Unix 时间戳。它会自动识别你输入的是哪种格式。  ## 使用须知 这个接口非常智能，能够自动识别输入格式：  - **输入时间戳**：支持10位秒级（如 &#x60;1672531200&#x60;）和13位毫秒级（如 &#x60;1672531200000&#x60;）。 - **输入日期字符串**：为了确保准确性，推荐使用 &#x60;YYYY-MM-DD HH:mm:ss&#x60; 标准格式（如 &#x60;2023-01-01 08:00:00&#x60;）。  &gt; [!TIP] &gt; 无论你输入哪种格式，响应中都会同时包含标准日期字符串和秒级Unix时间戳，方便你按需取用。  ## 错误处理指南 - **400 Bad Request**: 如果你提供的 &#x60;time&#x60; 参数既不是有效的时间戳，也不是我们支持的日期格式，就会收到这个错误。请检查你的输入值。
     * @param time 一个智能时间参数，可传入Unix时间戳（10位或13位）或标准日期字符串（如 &#39;2023-10-27 10:30:00&#39;），系统将自动识别并转换。 (required)
     * @return ApiResponse&lt;GetConvertUnixtime200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 转换成功！响应中会同时包含标准日期字符串和秒级Unix时间戳，方便你使用。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 请求失败。请检查你提供的 &#x60;time&#x60; 参数是否是有效的时间戳或我们支持的日期格式（YYYY-MM-DD HH:mm:ss）。 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetConvertUnixtime200Response> getConvertUnixtimeWithHttpInfo(@javax.annotation.Nonnull String time) throws ApiException {
        okhttp3.Call localVarCall = getConvertUnixtimeValidateBeforeCall(time, null);
        Type localVarReturnType = new TypeToken<GetConvertUnixtime200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Unix时间戳与日期字符串双向转换 (asynchronously)
     * 时间戳和日期字符串，哪个用着更顺手？别纠结了，这个接口让你轻松拥有两种格式！  ## 功能概述 这是一个非常智能的转换器。你给它一个 Unix 时间戳，它还你一个人类可读的日期时间；你给它一个日期时间字符串，它还你一个 Unix 时间戳。它会自动识别你输入的是哪种格式。  ## 使用须知 这个接口非常智能，能够自动识别输入格式：  - **输入时间戳**：支持10位秒级（如 &#x60;1672531200&#x60;）和13位毫秒级（如 &#x60;1672531200000&#x60;）。 - **输入日期字符串**：为了确保准确性，推荐使用 &#x60;YYYY-MM-DD HH:mm:ss&#x60; 标准格式（如 &#x60;2023-01-01 08:00:00&#x60;）。  &gt; [!TIP] &gt; 无论你输入哪种格式，响应中都会同时包含标准日期字符串和秒级Unix时间戳，方便你按需取用。  ## 错误处理指南 - **400 Bad Request**: 如果你提供的 &#x60;time&#x60; 参数既不是有效的时间戳，也不是我们支持的日期格式，就会收到这个错误。请检查你的输入值。
     * @param time 一个智能时间参数，可传入Unix时间戳（10位或13位）或标准日期字符串（如 &#39;2023-10-27 10:30:00&#39;），系统将自动识别并转换。 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 转换成功！响应中会同时包含标准日期字符串和秒级Unix时间戳，方便你使用。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 请求失败。请检查你提供的 &#x60;time&#x60; 参数是否是有效的时间戳或我们支持的日期格式（YYYY-MM-DD HH:mm:ss）。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getConvertUnixtimeAsync(@javax.annotation.Nonnull String time, final ApiCallback<GetConvertUnixtime200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getConvertUnixtimeValidateBeforeCall(time, _callback);
        Type localVarReturnType = new TypeToken<GetConvertUnixtime200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postConvertJson
     * @param postConvertJsonRequest 这是一个JSON对象，里面必须包含一个名为 &#x60;content&#x60; 的字段。这个字段的值，就是你希望格式化的、原始的JSON字符串。 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 格式化成功！返回一个包含美化后JSON字符串的对象。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 请求失败。这通常意味着你提供的 &#x60;content&#x60; 字符串不是一个合法的JSON格式。请检查括号、引号是否匹配，以及末尾是否有多余的逗号等常见错误。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postConvertJsonCall(@javax.annotation.Nonnull PostConvertJsonRequest postConvertJsonRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = postConvertJsonRequest;

        // create path and map variables
        String localVarPath = "/convert/json";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postConvertJsonValidateBeforeCall(@javax.annotation.Nonnull PostConvertJsonRequest postConvertJsonRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'postConvertJsonRequest' is set
        if (postConvertJsonRequest == null) {
            throw new ApiException("Missing the required parameter 'postConvertJsonRequest' when calling postConvertJson(Async)");
        }

        return postConvertJsonCall(postConvertJsonRequest, _callback);

    }

    /**
     * 美化并格式化JSON字符串
     * 还在为一团乱麻的 JSON 字符串头疼吗？这个接口能瞬间让它变得井井有条，赏心悦目。  ## 功能概述 你只需要提供一个原始的、可能是压缩过的或者格式混乱的 JSON 字符串，这个 API 就会返回一个经过美化（带标准缩进和换行）的版本。这在调试 API 响应、或者需要在前端界面清晰展示 JSON 数据时非常有用。  ## 使用须知 &gt; [!NOTE] &gt; **请求格式** &gt; 请注意，待格式化的 JSON 字符串需要被包裹在另一个 JSON 对象中，作为 &#x60;content&#x60; 字段的值提交。具体格式请参考请求体示例。  ## 错误处理指南 - **400 Bad Request**: 最常见的原因是你提供的 &#x60;content&#x60; 字符串本身不是一个有效的 JSON。请仔细检查括号、引号是否正确闭合，或者有没有多余的逗号等语法错误。
     * @param postConvertJsonRequest 这是一个JSON对象，里面必须包含一个名为 &#x60;content&#x60; 的字段。这个字段的值，就是你希望格式化的、原始的JSON字符串。 (required)
     * @return PostConvertJson200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 格式化成功！返回一个包含美化后JSON字符串的对象。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 请求失败。这通常意味着你提供的 &#x60;content&#x60; 字符串不是一个合法的JSON格式。请检查括号、引号是否匹配，以及末尾是否有多余的逗号等常见错误。 </td><td>  -  </td></tr>
     </table>
     */
    public PostConvertJson200Response postConvertJson(@javax.annotation.Nonnull PostConvertJsonRequest postConvertJsonRequest) throws ApiException {
        ApiResponse<PostConvertJson200Response> localVarResp = postConvertJsonWithHttpInfo(postConvertJsonRequest);
        return localVarResp.getData();
    }

    /**
     * 美化并格式化JSON字符串
     * 还在为一团乱麻的 JSON 字符串头疼吗？这个接口能瞬间让它变得井井有条，赏心悦目。  ## 功能概述 你只需要提供一个原始的、可能是压缩过的或者格式混乱的 JSON 字符串，这个 API 就会返回一个经过美化（带标准缩进和换行）的版本。这在调试 API 响应、或者需要在前端界面清晰展示 JSON 数据时非常有用。  ## 使用须知 &gt; [!NOTE] &gt; **请求格式** &gt; 请注意，待格式化的 JSON 字符串需要被包裹在另一个 JSON 对象中，作为 &#x60;content&#x60; 字段的值提交。具体格式请参考请求体示例。  ## 错误处理指南 - **400 Bad Request**: 最常见的原因是你提供的 &#x60;content&#x60; 字符串本身不是一个有效的 JSON。请仔细检查括号、引号是否正确闭合，或者有没有多余的逗号等语法错误。
     * @param postConvertJsonRequest 这是一个JSON对象，里面必须包含一个名为 &#x60;content&#x60; 的字段。这个字段的值，就是你希望格式化的、原始的JSON字符串。 (required)
     * @return ApiResponse&lt;PostConvertJson200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 格式化成功！返回一个包含美化后JSON字符串的对象。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 请求失败。这通常意味着你提供的 &#x60;content&#x60; 字符串不是一个合法的JSON格式。请检查括号、引号是否匹配，以及末尾是否有多余的逗号等常见错误。 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PostConvertJson200Response> postConvertJsonWithHttpInfo(@javax.annotation.Nonnull PostConvertJsonRequest postConvertJsonRequest) throws ApiException {
        okhttp3.Call localVarCall = postConvertJsonValidateBeforeCall(postConvertJsonRequest, null);
        Type localVarReturnType = new TypeToken<PostConvertJson200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 美化并格式化JSON字符串 (asynchronously)
     * 还在为一团乱麻的 JSON 字符串头疼吗？这个接口能瞬间让它变得井井有条，赏心悦目。  ## 功能概述 你只需要提供一个原始的、可能是压缩过的或者格式混乱的 JSON 字符串，这个 API 就会返回一个经过美化（带标准缩进和换行）的版本。这在调试 API 响应、或者需要在前端界面清晰展示 JSON 数据时非常有用。  ## 使用须知 &gt; [!NOTE] &gt; **请求格式** &gt; 请注意，待格式化的 JSON 字符串需要被包裹在另一个 JSON 对象中，作为 &#x60;content&#x60; 字段的值提交。具体格式请参考请求体示例。  ## 错误处理指南 - **400 Bad Request**: 最常见的原因是你提供的 &#x60;content&#x60; 字符串本身不是一个有效的 JSON。请仔细检查括号、引号是否正确闭合，或者有没有多余的逗号等语法错误。
     * @param postConvertJsonRequest 这是一个JSON对象，里面必须包含一个名为 &#x60;content&#x60; 的字段。这个字段的值，就是你希望格式化的、原始的JSON字符串。 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 格式化成功！返回一个包含美化后JSON字符串的对象。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 请求失败。这通常意味着你提供的 &#x60;content&#x60; 字符串不是一个合法的JSON格式。请检查括号、引号是否匹配，以及末尾是否有多余的逗号等常见错误。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postConvertJsonAsync(@javax.annotation.Nonnull PostConvertJsonRequest postConvertJsonRequest, final ApiCallback<PostConvertJson200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = postConvertJsonValidateBeforeCall(postConvertJsonRequest, _callback);
        Type localVarReturnType = new TypeToken<PostConvertJson200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
