/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.GetGithubRepo200Response;
import org.openapitools.client.model.GetGithubRepo400Response;
import org.openapitools.client.model.GetGithubRepo502Response;
import org.openapitools.client.model.GetSocialBilibiliArchives200Response;
import org.openapitools.client.model.GetSocialBilibiliArchives400Response;
import org.openapitools.client.model.GetSocialBilibiliArchives404Response;
import org.openapitools.client.model.GetSocialBilibiliArchives500Response;
import org.openapitools.client.model.GetSocialBilibiliLiveroom200Response;
import org.openapitools.client.model.GetSocialBilibiliReplies200Response;
import org.openapitools.client.model.GetSocialBilibiliUserinfo200Response;
import org.openapitools.client.model.GetSocialBilibiliUserinfo400Response;
import org.openapitools.client.model.GetSocialBilibiliUserinfo404Response;
import org.openapitools.client.model.GetSocialBilibiliUserinfo502Response;
import org.openapitools.client.model.GetSocialBilibiliVideoinfo200Response;
import org.openapitools.client.model.GetSocialQqGroupinfo200Response;
import org.openapitools.client.model.GetSocialQqGroupinfo400Response;
import org.openapitools.client.model.GetSocialQqGroupinfo404Response;
import org.openapitools.client.model.GetSocialQqGroupinfo500Response;
import org.openapitools.client.model.GetSocialQqUserinfo200Response;
import org.openapitools.client.model.GetSocialQqUserinfo400Response;
import org.openapitools.client.model.GetSocialQqUserinfo404Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SocialApi
 */
@Disabled
public class SocialApiTest {

    private final SocialApi api = new SocialApi();

    /**
     * 获取GitHub仓库信息
     *
     * 需要快速获取一个GitHub仓库的核心信息？这个接口为你聚合了最有价值的数据，避免了多次调用GitHub官方API的麻烦，并且内置了缓存优化，速度更快、更稳定。  ### 聚合高价值数据 一次请求，即可获得以下信息： - **核心指标**: &#x60;star&#x60;, &#x60;fork&#x60;, &#x60;open_issues&#x60; 等关键统计数据。 - **项目详情**: 描述、主页、分支、语言、话题标签、开源协议。 - **参与者信息**: 获取协作者(&#x60;collaborators&#x60;)和推断的维护者(&#x60;maintainers&#x60;)列表，包括他们的公开邮箱（如果可用）。  &gt; [!NOTE] &gt; &#x60;collaborators&#x60; 字段在私有仓库或权限受限时可能为空。&#x60;maintainers&#x60; 是根据最新提交记录推断的，仅供参考。  ### 性能与稳定性 我们内置了多级缓存，有效避免触发GitHub的API速率限制。对于需要更高请求额度的用户，可以联系我们定制接口。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getGithubRepoTest() throws ApiException {
        String repo = null;
        GetGithubRepo200Response response = api.getGithubRepo(repo);
        // TODO: test validations
    }

    /**
     * 获取Bilibili用户投稿列表
     *
     * 想要获取UP主的所有投稿视频？或者想在你的应用里展示创作者的作品集？这个接口能帮你轻松实现。  ## 功能概述 通过用户的 &#x60;mid&#x60;（用户ID），你可以获取该UP主的投稿视频列表。接口支持关键词搜索、分页加载和多种排序方式，让你能够灵活地展示和分析创作者的内容。  ## 参数说明 - **&#x60;mid&#x60; (用户ID)**: B站用户的mid，必填参数。 - **&#x60;keywords&#x60; (搜索关键词)**: 可选，用于在该UP主的投稿中搜索特定关键词。 - **&#x60;orderby&#x60; (排序方式)**:    - &#x60;pubdate&#x60;: 按最新发布排序（默认）   - &#x60;views&#x60;: 按最多播放排序 - **&#x60;ps&#x60; (每页条数)**: 默认20条。 - **&#x60;pn&#x60; (页码)**: 默认1，用于分页。  ## 响应体字段说明 - **&#x60;total&#x60; (总稿件数)**: UP主的投稿总数。 - **&#x60;page&#x60; (当前页码)**: 当前返回的页码。 - **&#x60;size&#x60; (每页数量)**: 每页返回的视频数量。 - **&#x60;videos&#x60; (视频列表)**: 包含当前页的所有视频信息：   - &#x60;aid&#x60;: 视频的AV号   - &#x60;bvid&#x60;: 视频的BV号   - &#x60;title&#x60;: 视频标题   - &#x60;cover&#x60;: 封面URL   - &#x60;duration&#x60;: 时长（秒）   - &#x60;play_count&#x60;: 播放量   - &#x60;publish_time&#x60;: 发布时间戳   - &#x60;create_time&#x60;: 创建时间戳   - &#x60;state&#x60;: 视频状态   - &#x60;is_ugc_pay&#x60;: 是否付费视频（0&#x3D;免费，1&#x3D;付费）   - &#x60;is_interactive&#x60;: 是否为互动视频
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSocialBilibiliArchivesTest() throws ApiException {
        String mid = null;
        String keywords = null;
        String orderby = null;
        String ps = null;
        String pn = null;
        GetSocialBilibiliArchives200Response response = api.getSocialBilibiliArchives(mid, keywords, orderby, ps, pn);
        // TODO: test validations
    }

    /**
     * 获取Bilibili直播间信息
     *
     * 想知道你喜欢的主播开播了吗？或者想在你的应用里集成B站直播间状态？这个接口能满足你。  ## 功能概述 这是一个智能接口，你可以用主播的 &#x60;mid&#x60; (用户ID) 或者直播间的 &#x60;room_id&#x60; (长号或短号)来查询。它会返回直播间的详细信息，包括是否在直播、标题、封面、人气、分区等。  ## 响应体字段说明 - **&#x60;live_status&#x60; (直播状态)**: &#x60;0&#x60; 代表未开播，&#x60;1&#x60; 代表直播中，&#x60;2&#x60; 代表轮播中。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSocialBilibiliLiveroomTest() throws ApiException {
        String mid = null;
        String roomId = null;
        GetSocialBilibiliLiveroom200Response response = api.getSocialBilibiliLiveroom(mid, roomId);
        // TODO: test validations
    }

    /**
     * 获取Bilibili视频评论
     *
     * 想要分析B站视频的评论区？这个接口可以帮你轻松获取评论数据，包括热门评论和最新评论，还支持分页加载。  ## 功能概述 通过视频的 &#x60;oid&#x60;（通常就是视频的&#x60;aid&#x60;），你可以分页获取该视频的评论区内容。你可以指定排序方式和分页参数，来精确地获取你需要的数据。  ## 参数说明 - **&#x60;sort&#x60; (排序方式)**: &#x60;0&#x60;&#x3D;按时间排序, &#x60;1&#x60;&#x3D;按点赞数排序, &#x60;2&#x60;&#x3D;按回复数排序。默认为按时间排序。  ## 响应体字段说明 - **&#x60;hots&#x60; (热门评论)**: 仅在请求第一页时，可能会返回热门评论列表。其结构与 &#x60;replies&#x60; 中的对象一致。 - **&#x60;replies&#x60; (评论列表)**: 这是一个数组，包含了当前页的评论。其中：   - &#x60;root&#x60;: 指向根评论的ID。如果评论本身就是根评论，则为 &#x60;0&#x60;。   - &#x60;parent&#x60;: 指向该条回复所回复的上一级评论ID。如果评论是根评论，则为 &#x60;0&#x60;。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSocialBilibiliRepliesTest() throws ApiException {
        String oid = null;
        String sort = null;
        String ps = null;
        String pn = null;
        GetSocialBilibiliReplies200Response response = api.getSocialBilibiliReplies(oid, sort, ps, pn);
        // TODO: test validations
    }

    /**
     * 查询Bilibili用户信息
     *
     * 想在你的应用里集成B站用户资料展示？这个接口可以轻松获取用户的公开信息。  ## 功能概述 通过一个用户的UID（那一串纯数字ID），你可以查询到该用户的昵称、性别、头像、等级、签名等一系列公开的基本信息。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSocialBilibiliUserinfoTest() throws ApiException {
        String uid = null;
        GetSocialBilibiliUserinfo200Response response = api.getSocialBilibiliUserinfo(uid);
        // TODO: test validations
    }

    /**
     * 获取Bilibili视频详细信息
     *
     * 想在你的应用里展示B站视频的详细信息吗？无论是封面、标题，还是播放量、UP主信息，这个接口都能一网打尽。  ## 功能概述 通过提供视频的 &#x60;aid&#x60; 或 &#x60;bvid&#x60;，你可以获取到该视频的完整元数据，包括多P信息、UP主资料、数据统计等。  ## 响应体字段说明 - **&#x60;copyright&#x60; (视频类型)**: &#x60;1&#x60; 代表原创，&#x60;2&#x60; 代表转载。 - **&#x60;owner&#x60; (UP主信息)**: 包含 &#x60;mid&#x60;, &#x60;name&#x60;, &#x60;face&#x60; 等UP主的基本资料。 - **&#x60;stat&#x60; (数据统计)**: 包含了播放、弹幕、评论、点赞、投币、收藏、分享等核心数据。 - **&#x60;pages&#x60; (分P列表)**: 这是一个数组，包含了视频的每一个分P的信息，即使是单P视频也会有一个元素。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSocialBilibiliVideoinfoTest() throws ApiException {
        String aid = null;
        String bvid = null;
        GetSocialBilibiliVideoinfo200Response response = api.getSocialBilibiliVideoinfo(aid, bvid);
        // TODO: test validations
    }

    /**
     * 获取QQ群名称、头像、简介
     *
     * 想在你的应用里展示QQ群信息？这个接口让你轻松获取群名称、群头像、群简介等公开信息。它能帮你快速构建社群导航站、群聊推荐系统，或是为你的数据分析工具提供可靠的数据源。无论是展示群聊卡片、生成加群链接，还是进行社群数据统计，这个接口都能满足你的需求。  &gt; [!VIP] &gt; 本API目前处于**限时免费**阶段，我们鼓励开发者集成和测试。未来，它将转为付费API，为用户提供更稳定和强大的服务。  ## 功能概述 你只需要提供一个QQ群号（5-12位纯数字），接口就会返回该群的完整公开信息。我们会先验证群号的有效性，确保返回的数据准确可靠。接口的响应速度快，数据结构清晰，非常适合集成到各类应用场景中。  ## 返回数据说明 接口会返回以下QQ群的关键信息： - **群基础信息**: 包括群号、群名称，让你能够准确识别和展示群聊。 - **视觉素材**: 提供群头像URL（标准100x100尺寸），可直接用于在你的界面中展示群聊图标。 - **群介绍资料**: 包含群描述/简介和群标签，帮助用户了解群聊的主题和特色。 - **便捷入口**: 返回加群链接（二维码URL），方便用户一键加入感兴趣的群聊。 - **数据时效**: 提供最后更新时间戳，让你了解数据的新鲜度。  所有返回的数据都遵循标准的JSON格式，字段命名清晰，便于解析和使用。无论你是在做网页端、移动端还是后端服务，都能轻松集成。
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSocialQqGroupinfoTest() throws ApiException {
        String groupId = null;
        GetSocialQqGroupinfo200Response response = api.getSocialQqGroupinfo(groupId);
        // TODO: test validations
    }

    /**
     * 独家获取QQ号头像、昵称
     *
     * 这是一个功能丰富的QQ用户信息查询接口，能够获取QQ用户的详细公开信息。  &gt; [!VIP] &gt; 我们在近日优化了此接口，速度应该会更加快了。   ## 功能概述 通过QQ号查询用户的详细信息，包括基础资料、等级信息、VIP状态等。返回的信息丰富全面，适合用于用户画像分析、社交应用集成等场景。  ## 数据字段说明 - **基础信息**: 昵称、个性签名、头像、年龄、性别 - **联系信息**: QQ邮箱、个性域名(QID) - **等级信息**: QQ等级、VIP状态和等级 - **时间信息**: 注册时间、最后更新时间
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSocialQqUserinfoTest() throws ApiException {
        String qq = null;
        GetSocialQqUserinfo200Response response = api.getSocialQqUserinfo(qq);
        // TODO: test validations
    }

}
