/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetHistoryProgrammerToday200ResponseEventsInner
 */
public class GetHistoryProgrammerToday200ResponseEventsInnerTest {
    private final GetHistoryProgrammerToday200ResponseEventsInner model = new GetHistoryProgrammerToday200ResponseEventsInner();

    /**
     * Model tests for GetHistoryProgrammerToday200ResponseEventsInner
     */
    @Test
    public void testGetHistoryProgrammerToday200ResponseEventsInner() {
        // TODO: test GetHistoryProgrammerToday200ResponseEventsInner
    }

    /**
     * Test the property 'year'
     */
    @Test
    public void yearTest() {
        // TODO: test year
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'importance'
     */
    @Test
    public void importanceTest() {
        // TODO: test importance
    }

    /**
     * Test the property 'relevanceScore'
     */
    @Test
    public void relevanceScoreTest() {
        // TODO: test relevanceScore
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
