/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetMiscDistrict200ResponseResultsInnerCenter
 */
public class GetMiscDistrict200ResponseResultsInnerCenterTest {
    private final GetMiscDistrict200ResponseResultsInnerCenter model = new GetMiscDistrict200ResponseResultsInnerCenter();

    /**
     * Model tests for GetMiscDistrict200ResponseResultsInnerCenter
     */
    @Test
    public void testGetMiscDistrict200ResponseResultsInnerCenter() {
        // TODO: test GetMiscDistrict200ResponseResultsInnerCenter
    }

    /**
     * Test the property 'lat'
     */
    @Test
    public void latTest() {
        // TODO: test lat
    }

    /**
     * Test the property 'lng'
     */
    @Test
    public void lngTest() {
        // TODO: test lng
    }

}
