/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetMiscWeather200ResponseLifeIndicesClothing
 */
public class GetMiscWeather200ResponseLifeIndicesClothingTest {
    private final GetMiscWeather200ResponseLifeIndicesClothing model = new GetMiscWeather200ResponseLifeIndicesClothing();

    /**
     * Model tests for GetMiscWeather200ResponseLifeIndicesClothing
     */
    @Test
    public void testGetMiscWeather200ResponseLifeIndicesClothing() {
        // TODO: test GetMiscWeather200ResponseLifeIndicesClothing
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'brief'
     */
    @Test
    public void briefTest() {
        // TODO: test brief
    }

    /**
     * Test the property 'advice'
     */
    @Test
    public void adviceTest() {
        // TODO: test advice
    }

}
