/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GetMiscHolidayCalendar200ResponseDataNearbyNextInner;
import org.openapitools.client.model.GetMiscHolidayCalendar200ResponseDataNearbyPreviousInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetMiscHolidayCalendar200ResponseDataNearby
 */
public class GetMiscHolidayCalendar200ResponseDataNearbyTest {
    private final GetMiscHolidayCalendar200ResponseDataNearby model = new GetMiscHolidayCalendar200ResponseDataNearby();

    /**
     * Model tests for GetMiscHolidayCalendar200ResponseDataNearby
     */
    @Test
    public void testGetMiscHolidayCalendar200ResponseDataNearby() {
        // TODO: test GetMiscHolidayCalendar200ResponseDataNearby
    }

    /**
     * Test the property 'previous'
     */
    @Test
    public void previousTest() {
        // TODO: test previous
    }

    /**
     * Test the property 'next'
     */
    @Test
    public void nextTest() {
        // TODO: test next
    }

}
