/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetNetworkMyip200Response
 */
public class GetNetworkMyip200ResponseTest {
    private final GetNetworkMyip200Response model = new GetNetworkMyip200Response();

    /**
     * Model tests for GetNetworkMyip200Response
     */
    @Test
    public void testGetNetworkMyip200Response() {
        // TODO: test GetNetworkMyip200Response
    }

    /**
     * Test the property 'ip'
     */
    @Test
    public void ipTest() {
        // TODO: test ip
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'isp'
     */
    @Test
    public void ispTest() {
        // TODO: test isp
    }

    /**
     * Test the property 'llc'
     */
    @Test
    public void llcTest() {
        // TODO: test llc
    }

    /**
     * Test the property 'asn'
     */
    @Test
    public void asnTest() {
        // TODO: test asn
    }

    /**
     * Test the property 'latitude'
     */
    @Test
    public void latitudeTest() {
        // TODO: test latitude
    }

    /**
     * Test the property 'longitude'
     */
    @Test
    public void longitudeTest() {
        // TODO: test longitude
    }

    /**
     * Test the property 'beginip'
     */
    @Test
    public void beginipTest() {
        // TODO: test beginip
    }

    /**
     * Test the property 'endip'
     */
    @Test
    public void endipTest() {
        // TODO: test endip
    }

    /**
     * Test the property 'district'
     */
    @Test
    public void districtTest() {
        // TODO: test district
    }

}
