/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.EndpointsAggregate;
import org.openapitools.client.model.EndpointsAggregateEndpointsInner;
import org.openapitools.client.model.EndpointsAggregateUnaggregated;
import org.openapitools.client.model.SingleEndpoint;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetStatusUsage200Response
 */
public class GetStatusUsage200ResponseTest {
    private final GetStatusUsage200Response model = new GetStatusUsage200Response();

    /**
     * Model tests for GetStatusUsage200Response
     */
    @Test
    public void testGetStatusUsage200Response() {
        // TODO: test GetStatusUsage200Response
    }

    /**
     * Test the property 'endpoints'
     */
    @Test
    public void endpointsTest() {
        // TODO: test endpoints
    }

    /**
     * Test the property 'unaggregated'
     */
    @Test
    public void unaggregatedTest() {
        // TODO: test unaggregated
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

}
