/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetSocialBilibiliVideoinfo200ResponseStat
 */
public class GetSocialBilibiliVideoinfo200ResponseStatTest {
    private final GetSocialBilibiliVideoinfo200ResponseStat model = new GetSocialBilibiliVideoinfo200ResponseStat();

    /**
     * Model tests for GetSocialBilibiliVideoinfo200ResponseStat
     */
    @Test
    public void testGetSocialBilibiliVideoinfo200ResponseStat() {
        // TODO: test GetSocialBilibiliVideoinfo200ResponseStat
    }

    /**
     * Test the property 'view'
     */
    @Test
    public void viewTest() {
        // TODO: test view
    }

    /**
     * Test the property 'danmaku'
     */
    @Test
    public void danmakuTest() {
        // TODO: test danmaku
    }

    /**
     * Test the property 'reply'
     */
    @Test
    public void replyTest() {
        // TODO: test reply
    }

    /**
     * Test the property 'favorite'
     */
    @Test
    public void favoriteTest() {
        // TODO: test favorite
    }

    /**
     * Test the property 'coin'
     */
    @Test
    public void coinTest() {
        // TODO: test coin
    }

    /**
     * Test the property 'share'
     */
    @Test
    public void shareTest() {
        // TODO: test share
    }

    /**
     * Test the property 'like'
     */
    @Test
    public void likeTest() {
        // TODO: test like
    }

}
