/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetStatusUsage200ResponseAnyOf1
 */
public class GetStatusUsage200ResponseAnyOf1Test {
    private final GetStatusUsage200ResponseAnyOf1 model = new GetStatusUsage200ResponseAnyOf1();

    /**
     * Model tests for GetStatusUsage200ResponseAnyOf1
     */
    @Test
    public void testGetStatusUsage200ResponseAnyOf1() {
        // TODO: test GetStatusUsage200ResponseAnyOf1
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

}
