/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GetSocialBilibiliReplies200ResponsePage;
import org.openapitools.client.model.GetSocialBilibiliReplies200ResponseRepliesInner;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetSocialBilibiliReplies200Response
 */
public class GetSocialBilibiliReplies200ResponseTest {
    private final GetSocialBilibiliReplies200Response model = new GetSocialBilibiliReplies200Response();

    /**
     * Model tests for GetSocialBilibiliReplies200Response
     */
    @Test
    public void testGetSocialBilibiliReplies200Response() {
        // TODO: test GetSocialBilibiliReplies200Response
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'hots'
     */
    @Test
    public void hotsTest() {
        // TODO: test hots
    }

    /**
     * Test the property 'replies'
     */
    @Test
    public void repliesTest() {
        // TODO: test replies
    }

}
