/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner
 */
public class GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInnerTest {
    private final GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner model = new GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner();

    /**
     * Model tests for GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner
     */
    @Test
    public void testGetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner() {
        // TODO: test GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner
    }

    /**
     * Test the property 'aid'
     */
    @Test
    public void aidTest() {
        // TODO: test aid
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'desc'
     */
    @Test
    public void descTest() {
        // TODO: test desc
    }

    /**
     * Test the property 'weeklyRecommendNum'
     */
    @Test
    public void weeklyRecommendNumTest() {
        // TODO: test weeklyRecommendNum
    }

}
