/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetSocialBilibiliReplies200ResponseRepliesInnerContent
 */
public class GetSocialBilibiliReplies200ResponseRepliesInnerContentTest {
    private final GetSocialBilibiliReplies200ResponseRepliesInnerContent model = new GetSocialBilibiliReplies200ResponseRepliesInnerContent();

    /**
     * Model tests for GetSocialBilibiliReplies200ResponseRepliesInnerContent
     */
    @Test
    public void testGetSocialBilibiliReplies200ResponseRepliesInnerContent() {
        // TODO: test GetSocialBilibiliReplies200ResponseRepliesInnerContent
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
