/*
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Markdown;
import org.openapitools.client.model.PostTextMarkdownToHtml400ResponseOneOf;
import org.openapitools.client.model.PostTextMarkdownToHtml400ResponseOneOf1;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostTextMarkdownToHtml400Response
 */
public class PostTextMarkdownToHtml400ResponseTest {
    private final PostTextMarkdownToHtml400Response model = new PostTextMarkdownToHtml400Response();

    /**
     * Model tests for PostTextMarkdownToHtml400Response
     */
    @Test
    public void testPostTextMarkdownToHtml400Response() {
        // TODO: test PostTextMarkdownToHtml400Response
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
