/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostAiTranslate200ResponsePerformance
 */
public class PostAiTranslate200ResponsePerformanceTest {
    private final PostAiTranslate200ResponsePerformance model = new PostAiTranslate200ResponsePerformance();

    /**
     * Model tests for PostAiTranslate200ResponsePerformance
     */
    @Test
    public void testPostAiTranslate200ResponsePerformance() {
        // TODO: test PostAiTranslate200ResponsePerformance
    }

    /**
     * Test the property 'processingTimeMs'
     */
    @Test
    public void processingTimeMsTest() {
        // TODO: test processingTimeMs
    }

    /**
     * Test the property 'cacheHit'
     */
    @Test
    public void cacheHitTest() {
        // TODO: test cacheHit
    }

}
