/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostTextBase64Encode200Response
 */
public class PostTextBase64Encode200ResponseTest {
    private final PostTextBase64Encode200Response model = new PostTextBase64Encode200Response();

    /**
     * Model tests for PostTextBase64Encode200Response
     */
    @Test
    public void testPostTextBase64Encode200Response() {
        // TODO: test PostTextBase64Encode200Response
    }

    /**
     * Test the property 'encoded'
     */
    @Test
    public void encodedTest() {
        // TODO: test encoded
    }

}
