/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostSensitiveWordQuickCheck200Response
 */
public class PostSensitiveWordQuickCheck200ResponseTest {
    private final PostSensitiveWordQuickCheck200Response model = new PostSensitiveWordQuickCheck200Response();

    /**
     * Model tests for PostSensitiveWordQuickCheck200Response
     */
    @Test
    public void testPostSensitiveWordQuickCheck200Response() {
        // TODO: test PostSensitiveWordQuickCheck200Response
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'originalText'
     */
    @Test
    public void originalTextTest() {
        // TODO: test originalText
    }

    /**
     * Test the property 'maskedText'
     */
    @Test
    public void maskedTextTest() {
        // TODO: test maskedText
    }

    /**
     * Test the property 'forbiddenWords'
     */
    @Test
    public void forbiddenWordsTest() {
        // TODO: test forbiddenWords
    }

}
