/*
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostSearchAggregate200ResponseMetadataRequestParams
 */
public class PostSearchAggregate200ResponseMetadataRequestParamsTest {
    private final PostSearchAggregate200ResponseMetadataRequestParams model = new PostSearchAggregate200ResponseMetadataRequestParams();

    /**
     * Model tests for PostSearchAggregate200ResponseMetadataRequestParams
     */
    @Test
    public void testPostSearchAggregate200ResponseMetadataRequestParams() {
        // TODO: test PostSearchAggregate200ResponseMetadataRequestParams
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'timeoutMs'
     */
    @Test
    public void timeoutMsTest() {
        // TODO: test timeoutMs
    }

    /**
     * Test the property 'sort'
     */
    @Test
    public void sortTest() {
        // TODO: test sort
    }

}
