/*
 * UAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostTextMarkdownToHtml200ResponseData
 */
public class PostTextMarkdownToHtml200ResponseDataTest {
    private final PostTextMarkdownToHtml200ResponseData model = new PostTextMarkdownToHtml200ResponseData();

    /**
     * Model tests for PostTextMarkdownToHtml200ResponseData
     */
    @Test
    public void testPostTextMarkdownToHtml200ResponseData() {
        // TODO: test PostTextMarkdownToHtml200ResponseData
    }

    /**
     * Test the property 'html'
     */
    @Test
    public void htmlTest() {
        // TODO: test html
    }

}
