/*
 * UAPI
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostMiscDateDiff200Response
 */
public class PostMiscDateDiff200ResponseTest {
    private final PostMiscDateDiff200Response model = new PostMiscDateDiff200Response();

    /**
     * Model tests for PostMiscDateDiff200Response
     */
    @Test
    public void testPostMiscDateDiff200Response() {
        // TODO: test PostMiscDateDiff200Response
    }

    /**
     * Test the property 'days'
     */
    @Test
    public void daysTest() {
        // TODO: test days
    }

    /**
     * Test the property 'hours'
     */
    @Test
    public void hoursTest() {
        // TODO: test hours
    }

    /**
     * Test the property 'minutes'
     */
    @Test
    public void minutesTest() {
        // TODO: test minutes
    }

    /**
     * Test the property 'seconds'
     */
    @Test
    public void secondsTest() {
        // TODO: test seconds
    }

    /**
     * Test the property 'weeks'
     */
    @Test
    public void weeksTest() {
        // TODO: test weeks
    }

    /**
     * Test the property 'humanReadable'
     */
    @Test
    public void humanReadableTest() {
        // TODO: test humanReadable
    }

}
